 countryShops.afghanistan = [
  { id: 1, n: "finest supermarket", c: ["general", "groceries", "bakery"], u: "https://finest.af" },
  { id: 2, n: "golbahar center", c: ["general", "fashion", "electronics"], u: "https://golbahar.af" },
  { id: 3, n: "city walk mall", c: ["general", "fashion", "cafe"], u: "https://citywalk.af" },
  { id: 4, n: "kabul tech plaza", c: ["general", "electronics", "services"], u: "https://kabultech.af" },
  { id: 5, n: "afghan bazaar elite", c: ["general", "groceries", "fashion"], u: "https://afghanbazaar.af" },
  { id: 6, n: "herat style house", c: ["general", "fashion", "beauty"], u: "https://heratstyle.af" },
  { id: 7, n: "kandahar digital mart", c: ["general", "electronics", "home"], u: "https://kandahardigital.af" },
  { id: 8, n: "mazar fashion mall", c: ["general", "fashion", "kids"], u: "https://mazarmall.af" },
  { id: 9, n: "jalalabad daily mart", c: ["general", "groceries", "bakery"], u: "https://jalalabadstore.af" },
  { id: 10, n: "balkh gadget hub", c: ["general", "electronics", "mobile"], u: "https://balkhmart.af" },
  { id: 11, n: "pamir lifestyle center", c: ["general", "fashion", "home"], u: "https://pamirshop.af" },
  { id: 12, n: "ghazni fresh market", c: ["general", "groceries", "organic"], u: "https://ghaznineeds.af" },
  { id: 13, n: "kunduz electro world", c: ["general", "electronics", "appliances"], u: "https://kunduzhub.af" },
  { id: 14, n: "bamyan classic boutique", c: ["general", "fashion", "crafts"], u: "https://bamyancraft.af" },
  { id: 15, n: "logar super store", c: ["general", "groceries", "pharmacy"], u: "https://logarmarket.af" },
  { id: 16, n: "parwan retail point", c: ["general", "fashion", "sports"], u: "https://parwanretail.af" },
  { id: 17, n: "khost valley stores", c: ["general", "groceries", "hardware"], u: "https://khoststores.af" },
  { id: 18, n: "helmand modern mall", c: ["general", "fashion", "electronics"], u: "https://helmandmall.af" },
  { id: 19, n: "badakhshan food court", c: ["general", "groceries", "cafe"], u: "https://badakhshanfood.af" },
  { id: 20, n: "nimruz trade zone", c: ["general", "services", "electronics"], u: "https://nimruztrade.af" },
  { id: 21, n: "ghor daily mart", c: ["general", "groceries", "bakery"], u: "https://ghormart.af" },
  { id: 22, n: "farah city center", c: ["general", "fashion", "home"], u: "https://farahcenter.af" },
  { id: 23, n: "wardak goods store", c: ["general", "groceries", "household"], u: "https://wardakgoods.af" },
  { id: 24, n: "kapisa bazaar link", c: ["general", "fashion", "electronics"], u: "https://kapisalink.af" },
  { id: 25, n: "kunar wholesale mart", c: ["general", "groceries", "services"], u: "https://kunarmart.af" },
  { id: 26, n: "uruzgan modern store", c: ["general", "fashion", "beauty"], u: "https://uruzganstore.af" },
  { id: 27, n: "samangan shopping arcade", c: ["general", "fashion", "electronics"], u: "https://samanganarcade.af" },
  { id: 28, n: "faryab retail plaza", c: ["general", "groceries", "sports"], u: "https://faryabplaza.af" },
  { id: 29, n: "jowzjan market corner", c: ["general", "fashion", "kids"], u: "https://jowzjanmarket.af" },
  { id: 30, n: "takhar quick mart", c: ["general", "groceries", "bakery"], u: "https://takharmart.af" },
  { id: 31, n: "baghlan trade square", c: ["general", "electronics", "services"], u: "https://baghlantrade.af" },
  { id: 32, n: "nuristan village shop", c: ["general", "groceries", "home"], u: "https://nuristanshop.af" },
  { id: 33, n: "panjshir valley mall", c: ["general", "fashion", "cafe"], u: "https://panjshirmall.af" },
  { id: 34, n: "daykundi general store", c: ["general", "groceries", "pharmacy"], u: "https://daykundistore.af" },
  { id: 35, n: "paktika bazaar point", c: ["general", "fashion", "electronics"], u: "https://paktikabazaar.af" },
  { id: 36, n: "paktiya trading hub", c: ["general", "services", "hardware"], u: "https://paktiyahub.af" },
  { id: 37, n: "sar-e pol daily needs", c: ["general", "groceries", "bakery"], u: "https://sarepolneeds.af" },
  { id: 38, n: "badghis market lane", c: ["general", "fashion", "beauty"], u: "https://badghismarket.af" },
  { id: 39, n: "bagram supply center", c: ["general", "electronics", "services"], u: "https://bagramsupply.af" },
  { id: 40, n: "chaghcharan retail hub", c: ["general", "groceries", "home"], u: "https://chaghcharanhub.af" },
  { id: 41, n: "kabul riverside mall", c: ["general", "fashion", "cafe"], u: "https://kabulriver.af" },
  { id: 42, n: "herat ancient bazaar", c: ["general", "crafts", "fashion"], u: "https://heratbazaar.af" },
  { id: 43, n: "kandahar oasis store", c: ["general", "groceries", "kids"], u: "https://kandaharoasis.af" },
  { id: 44, n: "mazar golden square", c: ["general", "electronics", "fashion"], u: "https://mazarsquare.af" },
  { id: 45, n: "jalalabad green mart", c: ["general", "organic", "groceries"], u: "https://jalalabadgreen.af" },
  { id: 46, n: "balkh traditional hub", c: ["general", "crafts", "home"], u: "https://balkhtraditional.af" },
  { id: 47, n: "pamir mountain shops", c: ["general", "fashion", "sports"], u: "https://pamirmountain.af" },
  { id: 48, n: "ghazni history mall", c: ["general", "fashion", "electronics"], u: "https://ghaznimall.af" },
  { id: 49, n: "kunduz border mart", c: ["general", "groceries", "services"], u: "https://kunduzborder.af" },
  { id: 50, n: "bamyan valley center", c: ["general", "cafe", "fashion"], u: "https://bamyanvalley.af" }
];
