countryShops.bahrain = [ 
  { id: 51, n: "lulu hypermarket - hidd", c: "supermarket, food, general", u: "https://luluhypermarket.com", a: "" },
  { id: 52, n: "carrefour - bahrain mall", c: "supermarket, food, general", u: "https://carrefourbahrain.com", a: "" },
  { id: 53, n: "alosra supermarket - saar", c: "supermarket, food, general", u: "https://alosraonline.com", a: "" },
  { id: 54, n: "geant hypermarket - mall of dilmunia", c: "supermarket, electronics, home", u: "https://geantbahrain.com", a: "" },
  { id: 55, n: "ramez - salmabad", c: "supermarket, household, general", u: "https://ramez.net", a: "" },
  { id: 56, n: "sharaf dg - seef mall", c: "electronics, appliances, general", u: "https://bahrain.sharafdg.com", a: "" },
  { id: 57, n: "jumbo electronics - oasis mall", c: "electronics, home, general", u: "https://jumbo.bh", a: "" },
  { id: 58, n: "h&m - seef mall", c: "fashion, clothing, general", u: "https://bh.hm.com", a: "" },
  { id: 59, n: "zara - city centre bahrain", c: "fashion, clothing, general", u: "https://zara.com/bh", a: "" },
  { id: 60, n: "mango - seef mall", c: "fashion, clothing, general", u: "https://mango.com", a: "" },
  { id: 61, n: "next - city centre bahrain", c: "fashion, kids, general", u: "https://next.bh", a: "" },
  { id: 62, n: "mothercare - seef mall", c: "kids, baby, general", u: "https://mothercare.com", a: "" },
  { id: 63, n: "splash - city centre bahrain", c: "fashion, clothing, general", u: "https://splashfashions.com", a: "" },
  { id: 64, n: "max - city centre bahrain", c: "fashion, clothing, general", u: "https://maxfashion.com", a: "" },
  { id: 65, n: "centrepoint - oasis mall", c: "fashion, kids, beauty", u: "https://centrepointstores.com", a: "" },
  { id: 66, n: "babyshop - city centre bahrain", c: "kids, baby, general", u: "https://babyshopstores.com", a: "" },
  { id: 67, n: "sephora - seef mall", c: "beauty, cosmetics, general", u: "https://sephora.ae/en-bh", a: "" },
  { id: 68, n: "faces - city centre bahrain", c: "beauty, cosmetics, general", u: "https://faces.com", a: "" },
  { id: 69, n: "boots - seef mall", c: "health, beauty, general", u: "https://boots-me.com", a: "" },
  { id: 70, n: "magrabi optical - city centre", c: "health, eyewear, general", u: "https://magrabi.com", a: "" },
  { id: 71, n: "foot locker - seef mall", c: "sports, footwear, general", u: "https://footlocker.com.bh", a: "" },
  { id: 72, n: "sun & sand sports - city centre", c: "sports, fashion, general", u: "https://sssports.com", a: "" },
  { id: 73, n: "nike - seef mall", c: "sports, footwear, general", u: "https://nike.com", a: "" },
  { id: 74, n: "adidas - seef mall", c: "sports, fashion, general", u: "https://adidas.com", a: "" },
  { id: 75, n: "decathlon - oasis mall", c: "sports, outdoor, general", u: "https://decathlon.bh", a: "" },
  { id: 76, n: "ikea - manama", c: "furniture, home, general", u: "https://ikea.com/bh", a: "" },
  { id: 77, n: "home centre - city centre", c: "home, furniture, general", u: "https://homecentre.com", a: "" },
  { id: 78, n: "west elm - seef mall", c: "home, furniture, general", u: "https://westelm.me", a: "" },
  { id: 79, n: "jarir bookstore - seef mall", c: "stationery, electronics, books", u: "https://jarir.com", a: "" },
  { id: 80, n: "virgin megastore - seef mall", c: "electronics, entertainment, general", u: "https://virginmegastore.bh", a: "" },
  { id: 81, n: "toy world - city centre", c: "kids, games, general", u: "https://toyworld.bh", a: "" },
  { id: 82, n: "kiddy zone - city centre", c: "kids, games, general", u: "https://kiddyzone.com", a: "" },
  { id: 83, n: "bath & body works - seef mall", c: "beauty, fragrance, general", u: "https://bathandbodyworks.com.bh", a: "" },
  { id: 84, n: "victorias secret - seef mall", c: "fashion, lingerie, general", u: "https://victoriassecret.com.bh", a: "" },
  { id: 85, n: "burger king - manama", c: "food, dining, general", u: "https://burgerking.bh", a: "" },
  { id: 86, n: "pizza hut - juffair", c: "food, dining, general", u: "https://pizzahut.bh", a: "" },
  { id: 87, n: "starbucks - city centre bahrain", c: "food, cafe, general", u: "https://starbucks.bh", a: "" },
  { id: 88, n: "dunkin - seef mall", c: "food, cafe, general", u: "https://dunkin.bh", a: "" },
  { id: 89, n: "domino's - manama", c: "food, dining, general", u: "https://dominos.bh", a: "" },
  { id: 90, n: "kfc - juffair", c: "food, dining, general", u: "https://kfc.bh", a: "" },
  { id: 91, n: "al manai - seef mall", c: "home, appliances, general", u: "https://almanai.com", a: "" },
  { id: 92, n: "batelco - seef mall", c: "telecom, electronics, general", u: "https://batelco.com", a: "" },
  { id: 93, n: "stc - city centre", c: "telecom, electronics, general", u: "https://stc.com.bh", a: "" },
  { id: 94, n: "zafaran cafe - seef mall", c: "food, cafe, general", u: "https://zafarancafe.bh", a: "" },
  { id: 95, n: "coffee republic - juffair", c: "food, cafe, general", u: "https://coffeerepublic.bh", a: "" },
  { id: 96, n: "nasr pharmacy - seef mall", c: "health, pharmacy, general", u: "https://nasrpharmacy.com", a: "" },
  { id: 97, n: "al hilal hospital - muharraq", c: "medical, health, general", u: "https://alhilalhospital.com", a: "" },
  { id: 98, n: "bahrain cinema - seef mall", c: "entertainment, cinema, general", u: "https://cineco.com.bh", a: "" },
  { id: 99, n: "magic planet - seef mall", c: "kids, entertainment, general", u: "https://magicplanetmena.com", a: "" },
  { id: 100, n: "al jazira supermarket - juffair", c: "supermarket, food, general", u: "https://aljazira.bh", a: "" }
];
