countryShops.kuwait = [

   { id: 1, n: "sultan center", c: food,electronics,general, u: "https://sultan-center.com", a: "" },
  { id: 2, n: "x-cite", c: electronics,appliances,general, u: "https://xcite.com", a: "" },
  { id: 3, n: "alghanim electronics", c: electronics,home,general, u: "https://alghanim.com", a: "" },
  { id: 4, n: "boots pharmacy", c: health,beauty,general, u: "https://kw.boots.com", a: "" },
  { id: 5, n: "mothercare", c: kids,fashion,general, u: "https://kw.mothercare.com", a: "" },
  { id: 6, n: "sun & sand sports", c: sports,fashion,general, u: "https://kw.sssports.com", a: "" },
  { id: 7, n: "lulu hypermarket", c: food,electronics,general, u: "https://luluhypermarket.com/kw", a: "" },
  { id: 8, n: "boutiqaat", c: beauty,fashion,general, u: "https://boutiqaat.com", a: "" },
  { id: 9, n: "jarir bookstore", c: stationery,electronics,general, u: "https://jarir.com/kw", a: "" },
  { id: 10, n: "ikea", c: furniture,decor,general, u: "https://ikea.com.kw", a: "" },
  { id: 11, n: "west elm", c: furniture,home,general, u: "https://westelm.com.kw", a: "" },
  { id: 12, n: "pottery barn", c: furniture,decor,general, u: "https://potterybarn.com.kw", a: "" },
  { id: 13, n: "bath & body works", c: beauty,fragrance,general, u: "https://bathandbodyworks.com.kw", a: "" },
  { id: 14, n: "victorias secret", c: fashion,lingerie,general, u: "https://victoriassecret.com.kw", a: "" },
  { id: 15, n: "faces", c: beauty,skincare,general, u: "https://faces.com/kw", a: "" },
  { id: 16, n: "foot locker", c: sports,footwear,general, u: "https://footlocker.com.kw", a: "" },
  { id: 17, n: "adidas", c: sports,fashion,general, u: "https://adidas.com.kw", a: "" },
  { id: 18, n: "nike", c: sports,footwear,general, u: "https://nike.com/kw", a: "" },
  { id: 19, n: "decathlon", c: sports,outdoor,general, u: "https://decathlon.com.kw", a: "" },
  { id: 20, n: "asics", c: sports,footwear,general, u: "https://asics.com.kw", a: "" },
  { id: 21, n: "skechers", c: sports,fashion,general, u: "https://skechers.com.kw", a: "" },
  { id: 22, n: "next", c: fashion,kids,general, u: "https://next.com.kw", a: "" },
  { id: 23, n: "babyshop", c: kids,fashion,general, u: "https://babyshopstores.com/kw", a: "" },
  { id: 24, n: "centrepoint", c: fashion,kids,general, u: "https://centrepointstores.com/kw", a: "" },
  { id: 25, n: "mamas & papas", c: kids,furniture,general, u: "https://mamasandpapas.com.kw", a: "" },
  { id: 26, n: "toys r us", c: kids,games,general, u: "https://toysrus.com.kw", a: "" },
  { id: 27, n: "the children's place", c: kids,fashion,general, u: "https://childrensplace.com.kw", a: "" },
  { id: 28, n: "early learning centre", c: kids,education,general, u: "https://elc.com.kw", a: "" },
  { id: 29, n: "kiddy zone", c: kids,games,general, u: "https://kiddyzone.com/kw", a: "" },
  { id: 30, n: "miniso", c: home,lifestyle,general, u: "https://miniso.com.kw", a: "" },
  { id: 31, n: "pharmacy 4 u", c: health,skincare,general, u: "https://pharmacy4u.com.kw", a: "" },
  { id: 32, n: "dar al shifa", c: health,medical,general, u: "https://daralshifa.com.kw", a: "" },
  { id: 33, n: "al-rai pharmacy", c: health,beauty,general, u: "https://alrai.com.kw", a: "" },
  { id: 34, n: "ace hardware", c: home,tools,general, u: "https://acekuwait.com", a: "" },
  { id: 35, n: "grand hyper", c: food,electronics,general, u: "https://grandhyper.com/kw", a: "" },
  { id: 36, n: "nesto hypermarket", c: food,electronics,general, u: "https://nesto.com.kw", a: "" },
  { id: 37, n: "sharaf dg", c: electronics,appliances,general, u: "https://kuwait.sharafdg.com", a: "" },
  { id: 38, n: "best al-yousifi", c: electronics,appliances,general, u: "https://best.com.kw", a: "" },
  { id: 39, n: "magrabi optics", c: health,eyewear,general, u: "https://magrabi.com.kw", a: "" },
  { id: 40, n: "al jaber optics", c: health,eyewear,general, u: "https://aljaber.com.kw", a: "" },
  { id: 41, n: "yateem optician", c: health,eyewear,general, u: "https://yateem.com.kw", a: "" },
  { id: 42, n: "vision express", c: health,eyewear,general, u: "https://vision.com.kw", a: "" },
  { id: 43, n: "cake gallery", c: food,bakery,general, u: "https://cake.com.kw", a: "" },
  { id: 44, n: "delice bakery", c: food,bakery,general, u: "https://delice.com.kw", a: "" },
  { id: 45, n: "bread house", c: food,bakery,general, u: "https://bread.com.kw", a: "" },
  { id: 46, n: "batteel bakery", c: food,bakery,general, u: "https://batteel.com.kw", a: "" },
  { id: 47, n: "the range", c: home,garden,general, u: "https://therange.com.kw", a: "" },
  { id: 48, n: "taw9eel", c: food,essentials,general, u: "https://taw9eel.com", a: "" },
  { id: 49, n: "floward", c: gifts,flowers,general, u: "https://floward.com", a: "" },
  { id: 50, n: "fnp kuwait", c: gifts,flowers,general, u: "https://fnp.kw", a: "" }
  ];

