countryShops.kuwait = [
  { id: 101, n: "sultan center", c: ["food", "electronics", "general"], u: "https://sultan-center.com", a: "" },
  { id: 102, n: "x-cite", c: ["electronics", "appliances", "general"], u: "https://xcite.com", a: "" },
  { id: 103, n: "alghanim electronics", c: ["electronics", "home", "general"], u: "https://alghanim.com", a: "" },
  { id: 104, n: "boots pharmacy", c: ["health", "beauty", "general"], u: "https://kw.boots.com", a: "" },
  { id: 105, n: "mothercare", c: ["kids", "fashion", "general"], u: "https://kw.mothercare.com", a: "" },
  { id: 106, n: "sun & sand sports", c: ["sports", "fashion", "general"], u: "https://kw.sssports.com", a: "" },
  { id: 107, n: "lulu hypermarket", c: ["food", "electronics", "general"], u: "https://luluhypermarket.com/kw", a: "" },
  { id: 108, n: "boutiqaat", c: ["beauty", "fashion", "general"], u: "https://boutiqaat.com", a: "" },
  { id: 109, n: "jarir bookstore", c: ["stationery", "electronics", "general"], u: "https://jarir.com/kw", a: "" },
  { id: 110, n: "ikea", c: ["furniture", "decor", "general"], u: "https://ikea.com.kw", a: "" },
  { id: 111, n: "west elm", c: ["furniture", "home", "general"], u: "https://westelm.com.kw", a: "" },
  { id: 112, n: "pottery barn", c: ["furniture", "decor", "general"], u: "https://potterybarn.com.kw", a: "" },
  { id: 113, n: "bath & body works", c: ["beauty", "fragrance", "general"], u: "https://bathandbodyworks.com.kw", a: "" },
  { id: 114, n: "victorias secret", c: ["fashion", "lingerie", "general"], u: "https://victoriassecret.com.kw", a: "" },
  { id: 115, n: "faces", c: ["beauty", "skincare", "general"], u: "https://faces.com/kw", a: "" },
  { id: 116, n: "foot locker", c: ["sports", "footwear", "general"], u: "https://footlocker.com.kw", a: "" },
  { id: 117, n: "adidas", c: ["sports", "fashion", "general"], u: "https://adidas.com.kw", a: "" },
  { id: 118, n: "nike", c: ["sports", "footwear", "general"], u: "https://nike.com/kw", a: "" },
  { id: 119, n: "decathlon", c: ["sports", "outdoor", "general"], u: "https://decathlon.com.kw", a: "" },
  { id: 120, n: "asics", c: ["sports", "footwear", "general"], u: "https://asics.com.kw", a: "" },
  { id: 121, n: "skechers", c: ["sports", "fashion", "general"], u: "https://skechers.com.kw", a: "" },
  { id: 122, n: "next", c: ["fashion", "kids", "general"], u: "https://next.com.kw", a: "" },
  { id: 123, n: "babyshop", c: ["kids", "fashion", "general"], u: "https://babyshopstores.com/kw", a: "" },
  { id: 124, n: "centrepoint", c: ["fashion", "kids", "general"], u: "https://centrepointstores.com/kw", a: "" },
  { id: 125, n: "mamas & papas", c: ["kids", "furniture", "general"], u: "https://mamasandpapas.com.kw", a: "" },
  { id: 126, n: "toys r us", c: ["kids", "games", "general"], u: "https://toysrus.com.kw", a: "" },
  { id: 127, n: "the children's place", c: ["kids", "fashion", "general"], u: "https://childrensplace.com.kw", a: "" },
  { id: 128, n: "early learning centre", c: ["kids", "education", "general"], u: "https://elc.com.kw", a: "" },
  { id: 129, n: "kiddy zone", c: ["kids", "games", "general"], u: "https://kiddyzone.com/kw", a: "" },
  { id: 130, n: "miniso", c: ["home", "lifestyle", "general"], u: "https://miniso.com.kw", a: "" },
  { id: 131, n: "pharmacy 4 u", c: ["health", "skincare", "general"], u: "https://pharmacy4u.com.kw", a: "" },
  { id: 132, n: "dar al shifa", c: ["health", "medical", "general"], u: "https://daralshifa.com.kw", a: "" },
  { id: 133, n: "al-rai pharmacy", c: ["health", "beauty", "general"], u: "https://alrai.com.kw", a: "" },
  { id: 134, n: "ace hardware", c: ["home", "tools", "general"], u: "https://acekuwait.com", a: "" },
  { id: 135, n: "grand hyper", c: ["food", "electronics", "general"], u: "https://grandhyper.com/kw", a: "" },
  { id: 136, n: "nesto hypermarket", c: ["food", "electronics", "general"], u: "https://nesto.com.kw", a: "" },
  { id: 137, n: "sharaf dg", c: ["electronics", "appliances", "general"], u: "https://kuwait.sharafdg.com", a: "" },
  { id: 138, n: "best al-yousifi", c: ["electronics", "appliances", "general"], u: "https://best.com.kw", a: "" },
  { id: 139, n: "magrabi optics", c: ["health", "eyewear", "general"], u: "https://magrabi.com.kw", a: "" },
  { id: 140, n: "al jaber optics", c: ["health", "eyewear", "general"], u: "https://aljaber.com.kw", a: "" },
  { id: 141, n: "yateem optician", c: ["health", "eyewear", "general"], u: "https://yateem.com.kw", a: "" },
  { id: 142, n: "vision express", c: ["health", "eyewear", "general"], u: "https://vision.com.kw", a: "" },
  { id: 143, n: "cake gallery", c: ["food", "bakery", "general"], u: "https://cake.com.kw", a: "" },
  { id: 144, n: "delice bakery", c: ["food", "bakery", "general"], u: "https://delice.com.kw", a: "" },
  { id: 145, n: "bread house", c: ["food", "bakery", "general"], u: "https://bread.com.kw", a: "" },
  { id: 146, n: "batteel bakery", c: ["food", "bakery", "general"], u: "https://batteel.com.kw", a: "" },
  { id: 147, n: "the range", c: ["home", "garden", "general"], u: "https://therange.com.kw", a: "" },
  { id: 148, n: "taw9eel", c: ["food", "essentials", "general"], u: "https://taw9eel.com", a: "" },
  { id: 149, n: "floward", c: ["gifts", "flowers", "general"], u: "https://floward.com", a: "" },
  { id: 150, n: "fnp kuwait", c: ["gifts", "flowers", "general"], u: "https://fnp.kw", a: "" }
];
