countryShops.kuwait = [

  { id: 1, n: "sultan center", c: "food,general,electronics", u: "https://sultan-center.com", a: "" },
  { id: 2, n: "x-cite", c: "electronics,general", u: "https://xcite.com", a: "" },
  { id: 3, n: "alghanim electronics", c: "electronics,general", u: "https://alghanim.com", a: "" },
  { id: 4, n: "boots pharmacy", c: "health,beauty,general", u: "https://kw.boots.com", a: "" },
  { id: 5, n: "mothercare", c: "kids,fashion,general", u: "https://kw.mothercare.com", a: "" },
  { id: 6, n: "sun & sand sports", c: "sports,fashion,general", u: "https://kw.sssports.com", a: "" },
  { id: 7, n: "lulu hypermarket", c: "food,general,electronics", u: "https://luluhypermarket.com/kw", a: "" },
  { id: 8, n: "boutiqaat", c: "beauty,fashion,general", u: "https://boutiqaat.com", a: "" },
  { id: 9, n: "tamimi markets", c: "food,general", u: "https://tamimimarkets.com", a: "" },
  { id: 10, n: "jarir bookstore", c: "stationery,electronics,general", u: "https://jarir.com/kw", a: "" },
  { id: 11, n: "city centre", c: "food,general", u: "https://citycentre.com.kw", a: "" },
  { id: 12, n: "sephora", c: "beauty,general", u: "https://sephora.com.kw", a: "" },
  { id: 13, n: "h&m", c: "fashion,general", u: "https://kw.hm.com", a: "" },
  { id: 14, n: "zara", c: "fashion,general", u: "https://zara.com/kw", a: "" },
  { id: 15, n: "ikea", c: "furniture,general", u: "https://ikea.com.kw", a: "" },
  { id: 16, n: "west elm", c: "furniture,general", u: "https://westelm.com.kw", a: "" },
  { id: 17, n: "pottery barn", c: "furniture,general", u: "https://potterybarn.com.kw", a: "" },
  { id: 18, n: "american eagle", c: "fashion,general", u: "https://ae.com/kw", a: "" },
  { id: 19, n: "bath & body works", c: "beauty,general", u: "https://bathandbodyworks.com.kw", a: "" },
  { id: 20, n: "victorias secret", c: "fashion,general", u: "https://victoriassecret.com.kw", a: "" },
  { id: 21, n: "faces", c: "beauty,general", u: "https://faces.com/kw", a: "" },
  { id: 22, n: "foot locker", c: "sports,fashion,general", u: "https://footlocker.com.kw", a: "" },
  { id: 23, n: "adidas", c: "sports,fashion,general", u: "https://adidas.com.kw", a: "" },
  { id: 24, n: "nike", c: "sports,fashion,general", u: "https://nike.com/kw", a: "" },
  { id: 25, n: "decathlon", c: "sports,general", u: "https://decathlon.com.kw", a: "" },
  { id: 26, n: "asics", c: "sports,general", u: "https://asics.com.kw", a: "" },
  { id: 27, n: "skechers", c: "sports,fashion,general", u: "https://skechers.com.kw", a: "" },
  { id: 28, n: "next", c: "fashion,kids,general", u: "https://next.com.kw", a: "" },
  { id: 29, n: "gap", c: "fashion,general", u: "https://gap.com.kw", a: "" },
  { id: 30, n: "mango", c: "fashion,general", u: "https://mango.com/kw", a: "" },
  { id: 31, n: "bershka", c: "fashion,general", u: "https://bershka.com/kw", a: "" },
  { id: 32, n: "pull & bear", c: "fashion,general", u: "https://pullandbear.com/kw", a: "" },
  { id: 33, n: "stradivarius", c: "fashion,general", u: "https://stradivarius.com/kw", a: "" },
  { id: 34, n: "oysho", c: "fashion,general", u: "https://oysho.com/kw", a: "" },
  { id: 35, n: "massimo dutti", c: "fashion,general", u: "https://massimodutti.com/kw", a: "" },
  { id: 36, n: "lc waikiki", c: "fashion,general", u: "https://lcwaikiki.com/kw", a: "" },
  { id: 37, n: "defacto", c: "fashion,general", u: "https://defacto.com/kw", a: "" },
  { id: 38, n: "max", c: "fashion,general", u: "https://maxfashion.com/kw", a: "" },
  { id: 39, n: "splash", c: "fashion,general", u: "https://splashfashions.com/kw", a: "" },
  { id: 40, n: "babyshop", c: "kids,fashion,general", u: "https://babyshopstores.com/kw", a: "" },
  { id: 41, n: "centrepoint", c: "fashion,kids,general", u: "https://centrepointstores.com/kw", a: "" },
  { id: 42, n: "mamas & papas", c: "kids,general", u: "https://mamasandpapas.com.kw", a: "" },
  { id: 43, n: "toys r us", c: "kids,general", u: "https://toysrus.com.kw", a: "" },
  { id: 44, n: "the children's place", c: "kids,general", u: "https://childrensplace.com.kw", a: "" },
  { id: 45, n: "early learning centre", c: "kids,general", u: "https://elc.com.kw", a: "" },
  { id: 46, n: "kiddy zone", c: "kids,general", u: "https://kiddyzone.com/kw", a: "" },
  { id: 47, n: "miniso", c: "general,kids", u: "https://miniso.com.kw", a: "" },
  { id: 48, n: "pharmacy 4 u", c: "health,general", u: "https://pharmacy4u.com.kw", a: "" },
  { id: 49, n: "dar al shifa", c: "health,general", u: "https://daralshifa.com.kw", a: "" },
  { id: 50, n: "al-rai pharmacy", c: "health,general", u: "https://alrai.com.kw", a: "" }
]
