const countryShops = {
  oman: [
  // Part 1
  { id: 1, n: "lulu hypermarket muscat", c: "grocery, general, electronics", u: "https://www.luluhypermarket.com", a: "" },
  { id: 2, n: "carrefour muscat city centre", c: "grocery, general, electronics", u: "https://www.carrefouroman.com", a: "" },
  { id: 3, n: "sharaf dg muscat grand mall", c: "electronics", u: "https://oman.sharafdg.com", a: "" },
  { id: 4, n: "extra muscat ghala electronics", c: "electronics", u: "https://www.extra.com/en-om", a: "" },
  { id: 5, n: "e-max muscat grand mall", c: "electronics", u: "https://www.landmarkgroup.com", a: "" },
  { id: 6, n: "mi store muscat mall of oman", c: "electronics", u: "https://www.mi.com/om", a: "" },
  { id: 7, n: "virgin megastore muscat mall", c: "electronics, general", u: "https://www.virginmegastore.om", a: "" },
  { id: 8, n: "malabar gold and diamonds muscat", c: "fashion", u: "https://www.malabargoldanddiamonds.com", a: "" },
  { id: 9, n: "joyalukkas jewellery muscat ruwi", c: "fashion", u: "https://www.joyalukkas.com", a: "" },
  { id: 10, n: "kalyan jewellers muscat baushar", c: "fashion", u: "https://www.kalyanjewellers.net", a: "" },
  { id: 11, n: "centrepoint muscat city centre", c: "fashion, general", u: "https://www.centrepointstores.com", a: "" },
  { id: 12, n: "max fashion muscat avenues mall", c: "fashion", u: "https://www.maxfashion.com/om/en", a: "" },
  { id: 13, n: "splash muscat mall of oman", c: "fashion", u: "https://www.splashfashions.com", a: "" },
  { id: 14, n: "h and m muscat avenues mall", c: "fashion", u: "https://alshaya.com", a: "" },
  { id: 15, n: "zara muscat mall of oman", c: "fashion", u: "https://www.zara.com/om", a: "" },
  { id: 16, n: "m marks and spencer muscat grand", c: "fashion, grocery", u: "https://www.marksandspencer.com/om", a: "" },
  { id: 17, n: "adidas muscat city centre seeb", c: "fashion", u: "https://www.adidas.com/om/en", a: "" },
  { id: 18, n: "nike muscat mall of oman store", c: "fashion", u: "https://www.nike.com/om", a: "" },
  { id: 19, n: "ikea muscat avenues mall home", c: "general", u: "https://www.ikea.com/om/en", a: "" },
  { id: 20, n: "danube home muscat al khuwair", c: "general", u: "https://danubehome.com/oman/en", a: "" },
  { id: 21, n: "home centre muscat madinat qaboos", c: "general", u: "https://www.homecentre.com", a: "" },
  { id: 22, n: "starbucks muscat shatti al qurum", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 23, n: "costa coffee muscat ghubrah", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 24, n: "gloria jeans coffees muscat seeb", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 25, n: "caribou coffee muscat khuwair", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 26, n: "tim hortons muscat al mouj", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 27, n: "kfc muscat khuwair online food", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 28, n: "pizza hut muscat qurum delivery", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 29, n: "burger king muscat ghubrah shop", c: "general", u: "https://www.burgerking.om", a: "" },
  { id: 30, n: "hardees muscat seeb retail restaurant", c: "general", u: "https://www.hardees.om", a: "" },

  // Part 2
  { id: 31, n: "subway muscat baushar online", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 32, n: "baskin robbins muscat icecream", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 33, n: "dunkin muscat qurum coffee store", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 34, n: "dominos pizza muscat khuwair shop", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 35, n: "popeyes muscat seeb chicken", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 36, n: "texas chicken muscat ghubrah mall", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 37, n: "mcdonalds muscat shatti al qurum", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 38, n: "asics muscat mall of oman sports", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },
  { id: 39, n: "puma muscat city centre seeb mall", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 40, n: "reebok muscat avenues mall shop", c: "fashion", u: "https://www.reebok.com.om", a: "" },
  { id: 41, n: "under armour muscat mall of oman", c: "fashion", u: "https://www.underarmour.ae", a: "" },
  { id: 42, n: "aldo shoes muscat grand mall shop", c: "fashion", u: "https://www.aldoshoes.me/om/en", a: "" },
  { id: 43, n: "charles and keith muscat avenues", c: "fashion", u: "https://www.charleskeith.com/om", a: "" },
  { id: 44, n: "dune london muscat grand mall", c: "fashion", u: "https://www.dunelondon.me/om/en", a: "" },
  { id: 45, n: "e-mart muscat online grocery shop", c: "grocery, general", u: "https://www.emartoman.com", a: "" },
  { id: 46, n: "ourshopee muscat internet retail", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 47, n: "ubuy muscat online shopping app", c: "general", u: "https://www.ubuy.om/en", a: "" },
  { id: 48, n: "desertcart muscat delivery web", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 49, n: "namshi muscat fashion lifestyle", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 50, n: "6thstreet muscat shopping online", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },

  // Part 3
  { id: 51, n: "lulu hypermarket salalah center", c: "grocery, general, electronics", u: "https://www.luluhypermarket.com", a: "" },
  { id: 52, n: "carrefour salalah grand mall store", c: "grocery, general, electronics", u: "https://www.carrefouroman.com", a: "" },
  { id: 53, n: "sharaf dg salalah retail mall", c: "electronics", u: "https://oman.sharafdg.com", a: "" },
  { id: 54, n: "extra salalah digital appliance", c: "electronics", u: "https://www.extra.com/en-om", a: "" },
  { id: 55, n: "e-max salalah grand mall outlet", c: "electronics", u: "https://www.landmarkgroup.com", a: "" },
  { id: 56, n: "mi store salalah phone shop", c: "electronics", u: "https://www.mi.com/om", a: "" },
  { id: 57, n: "virgin megastore salalah center", c: "electronics, general", u: "https://www.virginmegastore.om", a: "" },
  { id: 58, n: "malabar gold and diamonds salalah", c: "fashion", u: "https://www.malabargoldanddiamonds.com", a: "" },
  { id: 59, n: "joyalukkas jewellery salalah shop", c: "fashion", u: "https://www.joyalukkas.com", a: "" },
  { id: 60, n: "kalyan jewellers salalah market", c: "fashion", u: "https://www.kalyanjewellers.net", a: "" },
  { id: 61, n: "centrepoint salalah grand mall", c: "fashion, general", u: "https://www.centrepointstores.com", a: "" },
  { id: 62, n: "max fashion salalah retail store", c: "fashion", u: "https://www.maxfashion.com/om/en", a: "" },
  { id: 63, n: "splash salalah garment boutique", c: "fashion", u: "https://www.splashfashions.com", a: "" },
  { id: 64, n: "h and m salalah grand mall clothes", c: "fashion", u: "https://alshaya.com", a: "" },
  { id: 65, n: "zara salalah style shop online", c: "fashion", u: "https://www.zara.com/om", a: "" },
  { id: 66, n: "marks and spencer salalah retail", c: "fashion, grocery", u: "https://www.marksandspencer.com/om", a: "" },
  { id: 67, n: "adidas salalah sportswear store", c: "fashion", u: "https://www.adidas.com/om/en", a: "" },
  { id: 68, n: "nike salalah running shoe shop", c: "fashion", u: "https://www.nike.com/om", a: "" },
  { id: 69, n: "ikea salalah home delivery shop", c: "general", u: "https://www.ikea.com/om/en", a: "" },
  { id: 70, n: "danube home salalah furniture", c: "general", u: "https://danubehome.com/oman/en", a: "" },
  { id: 71, n: "home centre salalah decor plaza", c: "general", u: "https://www.homecentre.com", a: "" },
  { id: 72, n: "starbucks salalah cafe branch", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 73, n: "costa coffee salalah express shop", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 74, n: "gloria jeans coffees salalah", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 75, n: "caribou coffee salalah hub store", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 76, n: "tim hortons salalah coffee plaza", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 77, n: "kfc salalah online food delivery", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 78, n: "pizza hut salalah home delivery", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 79, n: "burger king salalah market shop", c: "general", u: "https://www.burgerking.om", a: "" },
  { id: 80, n: "hardees salalah burger restaurant", c: "general", u: "https://www.hardees.om", a: "" },

  // Part 4
  { id: 81, n: "subway salalah web delivery shop", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 82, n: "baskin robbins salalah icecream", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 83, n: "dunkin salalah premium coffee", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 84, n: "dominos pizza salalah online store", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 85, n: "popeyes salalah fried chicken hub", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 86, n: "texas chicken salalah meal outlet", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 87, n: "mcdonalds salalah family restaurant", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 88, n: "asics salalah running gear store", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },
  { id: 89, n: "puma salalah workout apparel", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 90, n: "reebok salalah activewear shop", c: "fashion", u: "https://www.reebok.com.om", a: "" },
  { id: 91, n: "under armour salalah fitness hub", c: "fashion", u: "https://www.underarmour.ae", a: "" },
  { id: 92, n: "aldo shoes salalah leather fashion", c: "fashion", u: "https://www.aldoshoes.me/om/en", a: "" },
  { id: 93, n: "charles and keith salalah bag shop", c: "fashion", u: "https://www.charleskeith.com/om", a: "" },
  { id: 94, n: "dune london salalah elegant style", c: "fashion", u: "https://www.dunelondon.me/om/en", a: "" },
  { id: 95, n: "e-mart salalah provisions network", c: "grocery, general", u: "https://www.emartoman.com", a: "" },
  { id: 96, n: "ourshopee salalah smart electronics", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 97, n: "ubuy salalah cargo internet store", c: "general", u: "https://www.ubuy.om/en", a: "" },
  { id: 98, n: "desertcart salalah logistics retail", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 99, n: "namshi salalah cosmetic clothing", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 100, n: "6thstreet salalah footwear dynamic", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },

  // Part 5
  { id: 101, n: "lulu hypermarket sohar city mall", c: "grocery, general, electronics", u: "https://www.luluhypermarket.com", a: "" },
  { id: 102, n: "carrefour sohar plaza outlet store", c: "grocery, general, electronics", u: "https://www.carrefouroman.com", a: "" },
  { id: 103, n: "sharaf dg sohar tech supermarket", c: "electronics", u: "https://oman.sharafdg.com", a: "" },
  { id: 104, n: "extra sohar smart device retail", c: "electronics", u: "https://www.extra.com/en-om", a: "" },
  { id: 105, n: "e-max sohar lifestyle electronics", c: "electronics", u: "https://www.landmarkgroup.com", a: "" },
  { id: 106, n: "mi store sohar mobile gadget shop", c: "electronics", u: "https://www.mi.com/om", a: "" },
  { id: 107, n: "virgin megastore sohar book retail", c: "electronics, general", u: "https://www.virginmegastore.om", a: "" },
  { id: 108, n: "malabar gold and diamonds sohar", c: "fashion", u: "https://www.malabargoldanddiamonds.com", a: "" },
  { id: 109, n: "joyalukkas jewellery sohar center", c: "fashion", u: "https://www.joyalukkas.com", a: "" },
  { id: 110, n: "kalyan jewellers sohar main bazaar", c: "fashion", u: "https://www.kalyanjewellers.net", a: "" },
  { id: 111, n: "centrepoint sohar city centre mall", c: "fashion, general", u: "https://www.centrepointstores.com", a: "" },
  { id: 112, n: "max fashion sohar family shopping", c: "fashion", u: "https://www.maxfashion.com/om/en", a: "" },
  { id: 113, n: "splash sohar contemporary apparel", c: "fashion", u: "https://www.splashfashions.com", a: "" },
  { id: 114, n: "h and m sohar casual style plaza", c: "fashion", u: "https://alshaya.com", a: "" },
  { id: 115, n: "zara sohar trend retail clothes", c: "fashion", u: "https://www.zara.com/om", a: "" },
  { id: 116, n: "marks and spencer sohar standard", c: "fashion, grocery", u: "https://www.marksandspencer.com/om", a: "" },
  { id: 117, n: "adidas sohar soccer jersey store", c: "fashion", u: "https://www.adidas.com/om/en", a: "" },
  { id: 118, n: "nike sohar sportswear center mall", c: "fashion", u: "https://www.nike.com/om", a: "" },
  { id: 119, n: "ikea sohar home solution package", c: "general", u: "https://www.ikea.com/om/en", a: "" },
  { id: 120, n: "danube home sohar designer living", c: "general", u: "https://danubehome.com/oman/en", a: "" },
  { id: 121, n: "home centre sohar luxury bedding", c: "general", u: "https://www.homecentre.com", a: "" },
  { id: 122, n: "starbucks sohar coastal drive cafe", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 123, n: "costa coffee sohar corporate shop", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 124, n: "gloria jeans coffees sohar plaza", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 125, n: "caribou coffee sohar morning break", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 126, n: "tim hortons sohar express counter", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 127, n: "kfc sohar fried chicken bucket", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 128, n: "pizza hut sohar fast food online", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 129, n: "burger king sohar avenue drive in", c: "general", u: "https://www.burgerking.om", a: "" },
  { id: 130, n: "hardees sohar grilled burger hub", c: "general", u: "https://www.hardees.om", a: "" },

  // Part 6
  { id: 131, n: "subway sohar sandwich maker shop", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 132, n: "baskin robbins sohar sweet scoop", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 133, n: "dunkin sohar donut and coffee", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 134, n: "dominos pizza sohar cheesy crust", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 135, n: "popeyes sohar southern style food", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 136, n: "texas chicken sohar combo meal store", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 137, n: "mcdonalds sohar value meal center", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 138, n: "asics sohar athlete footwear shop", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },
  { id: 139, n: "puma sohar active shoe collection", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 140, n: "reebok sohar sport gear boutique", c: "fashion", u: "https://www.reebok.com.om", a: "" },
  { id: 141, n: "under armour sohar heavy workout", c: "fashion", u: "https://www.underarmour.ae", a: "" },
  { id: 142, n: "aldo shoes sohar casual boots shop", c: "fashion", u: "https://www.aldoshoes.me/om/en", a: "" },
  { id: 143, n: "charles and keith sohar accessories", c: "fashion", u: "https://www.charleskeith.com/om", a: "" },
  { id: 144, n: "dune london sohar executive styles", c: "fashion", u: "https://www.dunelondon.me/om/en", a: "" },
  { id: 145, n: "e-mart sohar retail store internet", c: "grocery, general", u: "https://www.emartoman.com", a: "" },
  { id: 146, n: "ourshopee sohar direct tech sales", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 147, n: "ubuy sohar cross border cargo", c: "general", u: "https://www.ubuy.om/en", a: "" },
  { id: 148, n: "desertcart sohar dynamic web store", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 149, n: "namshi sohar clothing collections", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 150, n: "6thstreet sohar apparel discount", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },

  // Part 7
  { id: 151, n: "nestle pure life muscat wholesale", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 152, n: "nestle pure life salalah supply", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 153, n: "nestle pure life sohar bulk store", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 154, n: "popeyes muscat qurum food plaza", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 155, n: "texas chicken muscat seeb branch", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 156, n: "ourshopee oman regional logistics", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 157, n: "ubuy oman global imports office", c: "general", u: "https://www.ubuy.om/en", a: "" },
  { id: 158, n: "desertcart oman internet trade hub", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 159, n: "namshi oman centralized fashion", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 160, n: "6thstreet oman application center", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },
  { id: 161, n: "lulu hypermarket nizwa mall", c: "grocery, general, electronics", u: "https://www.luluhypermarket.com", a: "" },
  { id: 162, n: "carrefour nizwa city grand center", c: "grocery, general, electronics", u: "https://www.carrefouroman.com", a: "" },
  { id: 163, n: "sharaf dg nizwa electronics hub", c: "electronics", u: "https://oman.sharafdg.com", a: "" },
  { id: 164, n: "extra nizwa smart appliance shop", c: "electronics", u: "https://www.extra.com/en-om", a: "" },
  { id: 165, n: "e-max nizwa lifestyle gadgets", c: "electronics", u: "https://www.landmarkgroup.com", a: "" },
  { id: 166, n: "mi store nizwa smartphone center", c: "electronics", u: "https://www.mi.com/om", a: "" },
  { id: 167, n: "virgin megastore nizwa book shop", c: "electronics, general", u: "https://www.virginmegastore.om", a: "" },
  { id: 168, n: "malabar gold and diamonds nizwa", c: "fashion", u: "https://www.malabargoldanddiamonds.com", a: "" },
  { id: 169, n: "joyalukkas jewellery nizwa bazaar", c: "fashion", u: "https://www.joyalukkas.com", a: "" },
  { id: 170, n: "kalyan jewellers nizwa town store", c: "fashion", u: "https://www.kalyanjewellers.net", a: "" },
  { id: 171, n: "centrepoint nizwa grand mall", c: "fashion, general", u: "https://www.centrepointstores.com", a: "" },
  { id: 172, n: "max fashion nizwa clothing plaza", c: "fashion", u: "https://www.maxfashion.com/om/en", a: "" },
  { id: 173, n: "splash nizwa contemporary design", c: "fashion", u: "https://www.splashfashions.com", a: "" },
  { id: 174, n: "h and m nizwa casual apparel mall", c: "fashion", u: "https://alshaya.com", a: "" },
  { id: 175, n: "zara nizwa designer garments", c: "fashion", u: "https://www.zara.com/om", a: "" },
  { id: 176, n: "marks and spencer nizwa branch", c: "fashion, grocery", u: "https://www.marksandspencer.com/om", a: "" },
  { id: 177, n: "adidas nizwa athletic wear store", c: "fashion", u: "https://www.adidas.com/om/en", a: "" },
  { id: 178, n: "nike nizwa running footwear shop", c: "fashion", u: "https://www.nike.com/om", a: "" },
  { id: 179, n: "ikea nizwa home delivery service", c: "general", u: "https://www.ikea.com/om/en", a: "" },
  { id: 180, n: "danube home nizwa furniture decor", c: "general", u: "https://danubehome.com/oman/en", a: "" },

  // Part 8
  { id: 181, n: "home centre nizwa standard design", c: "general", u: "https://www.homecentre.com", a: "" },
  { id: 182, n: "starbucks nizwa historic fort cafe", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 183, n: "costa coffee nizwa express plaza", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 184, n: "gloria jeans coffees nizwa hub", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 185, n: "caribou coffee nizwa city square", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 186, n: "tim hortons nizwa mall counter", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 187, n: "kfc nizwa chicken online order", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 188, n: "pizza hut nizwa home delivery shop", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 189, n: "burger king nizwa highway drive", c: "general", u: "https://www.burgerking.om", a: "" },
  { id: 190, n: "hardees nizwa charbroiled burger", c: "general", u: "https://www.hardees.om", a: "" },
  { id: 191, n: "subway nizwa healthy dining store", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 192, n: "baskin robbins nizwa icecream hub", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 193, n: "dunkin nizwa donuts coffee corner", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 194, n: "dominos pizza nizwa crust factory", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 195, n: "popeyes nizwa cajun chicken stall", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 196, n: "texas chicken nizwa family meals", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 197, n: "mcdonalds nizwa value food court", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 198, n: "asics nizwa sports footwear shop", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },
  { id: 199, n: "puma nizwa active garment mall", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 200, n: "reebok nizwa casual sneakers shop", c: "fashion", u: "https://www.reebok.com.om", a: "" },
  { id: 201, n: "under armour nizwa dynamic athletic", c: "fashion", u: "https://www.underarmour.ae", a: "" },
  { id: 202, n: "aldo shoes nizwa leather accessory", c: "fashion", u: "https://www.aldoshoes.me/om/en", a: "" },
  { id: 203, n: "charles and keith nizwa purse shop", c: "fashion", u: "https://www.charleskeith.com/om", a: "" },
  { id: 204, n: "dune london nizwa modern lifestyle", c: "fashion", u: "https://www.dunelondon.me/om/en", a: "" },
  { id: 205, n: "e-mart nizwa general provisions", c: "grocery, general", u: "https://www.emartoman.com", a: "" },
  { id: 206, n: "ourshopee nizwa online web shopping", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 207, n: "ubuy nizwa direct delivery service", c: "general", u: "https://www.ubuy.om/en", a: "" },
  { id: 208, n: "desertcart nizwa logistics portal", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 209, n: "namshi nizwa cosmetics and clothes", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 210, n: "6thstreet nizwa apparel digital app", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },

  // Part 9
  { id: 211, n: "nestle pure life nizwa distribution", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 212, n: "lulu hypermarket sur central mall", c: "grocery, general, electronics", u: "https://www.luluhypermarket.com", a: "" },
  { id: 213, n: "carrefour sur grand shopping plaza", c: "grocery, general, electronics", u: "https://www.carrefouroman.com", a: "" },
  { id: 214, n: "sharaf dg sur appliance digital", c: "electronics", u: "https://oman.sharafdg.com", a: "" },
  { id: 215, n: "extra sur tech gadget store mall", c: "electronics", u: "https://www.extra.com/en-om", a: "" },
  { id: 216, n: "e-max sur smart home electronics", c: "electronics", u: "https://www.landmarkgroup.com", a: "" },
  { id: 217, n: "mi store sur mobile accessory shop", c: "electronics", u: "https://www.mi.com/om", a: "" },
  { id: 218, n: "virgin megastore sur book media", c: "electronics, general", u: "https://www.virginmegastore.om", a: "" },
  { id: 219, n: "malabar gold and diamonds sur shop", c: "fashion", u: "https://www.malabargoldanddiamonds.com", a: "" },
  { id: 220, n: "joyalukkas jewellery sur coast road", c: "fashion", u: "https://www.joyalukkas.com", a: "" },
  { id: 221, n: "kalyan jewellers sur traditional gold", c: "fashion", u: "https://www.kalyanjewellers.net", a: "" },
  { id: 222, n: "centrepoint sur family retail center", c: "fashion, general", u: "https://www.centrepointstores.com", a: "" },
  { id: 223, n: "max fashion sur affordable garments", c: "fashion", u: "https://www.maxfashion.com/om/en", a: "" },
  { id: 224, n: "splash sur modern garment boutique", c: "fashion", u: "https://www.splashfashions.com", a: "" },
  { id: 225, n: "h and m sur casual fashion plaza", c: "fashion", u: "https://alshaya.com", a: "" },
  { id: 226, n: "zara sur latest clothing showroom", c: "fashion", u: "https://www.zara.com/om", a: "" },
  { id: 227, n: "marks and spencer sur boutique shop", c: "fashion, grocery", u: "https://www.marksandspencer.com/om", a: "" },
  { id: 228, n: "adidas sur sports gear retail store", c: "fashion", u: "https://www.adidas.com/om/en", a: "" },
  { id: 229, n: "nike sur running footwear plaza", c: "fashion", u: "https://www.nike.com/om", a: "" },
  { id: 230, n: "ikea sur home solution shipping", c: "general", u: "https://www.ikea.com/om/en", a: "" },
  { id: 231, n: "danube home sur furniture boutique", c: "general", u: "https://danubehome.com/oman/en", a: "" },
  { id: 232, n: "home centre sur stylish bedding shop", c: "general", u: "https://www.homecentre.com", a: "" },
  { id: 233, n: "starbucks sur harbor view coffee", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 234, n: "costa coffee sur seaside express", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 235, n: "gloria jeans coffees sur market", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 236, n: "caribou coffee sur morning blend", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 237, n: "tim hortons sur premium beverage", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 238, n: "kfc sur online food meal delivery", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 239, n: "pizza hut sur pan pizza retail shop", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 240, n: "burger king sur plaza food counter", c: "general", u: "https://www.burgerking.om", a: "" },

  // Part 10
  { id: 241, n: "hardees sur thickburger restaurant", c: "general", u: "https://www.hardees.om", a: "" },
  { id: 242, n: "subway sur fresh sandwich counter", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 243, n: "baskin robbins sur premium scoop", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 244, n: "dunkin sur gourmet donuts shop", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 245, n: "dominos pizza sur online home order", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 246, n: "popeyes sur Louisiana spicy chicken", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 247, n: "texas chicken sur crunchy value meal", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 248, n: "mcdonalds sur family dining avenue", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 249, n: "asics sur active running shoes", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },
  { id: 250, n: "puma sur track apparel and shoes", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 251, n: "reebok sur fitness workout store", c: "fashion", u: "https://www.reebok.com.om", a: "" },
  { id: 252, n: "under armour sur professional sport", c: "fashion", u: "https://www.underarmour.ae", a: "" },
  { id: 253, n: "aldo shoes sur elegant formal boots", c: "fashion", u: "https://www.aldoshoes.me/om/en", a: "" },
  { id: 254, n: "charles and keith sur ladies luxury", c: "fashion", u: "https://www.charleskeith.com/om", a: "" },
  { id: 255, n: "dune london sur modern leather art", c: "fashion", u: "https://www.dunelondon.me/om/en", a: "" },
  { id: 256, n: "e-mart sur online supermarket web", c: "grocery, general", u: "https://www.emartoman.com", a: "" },
  { id: 257, n: "ourshopee sur electronic warehouse", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 258, n: "ubuy sur international web trade", c: "general", u: "https://www.ubuy.om/en", a: "" },
  { id: 259, n: "desertcart sur premium dynamic trade", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 260, n: "namshi sur branded garments online", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 261, n: "6thstreet sur fashion catalog store", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },
  { id: 262, n: "nestle pure life sur regional supply", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 263, n: "lulu hypermarket ibri center mall", c: "grocery, general, electronics", u: "https://www.luluhypermarket.com", a: "" },
  { id: 264, n: "carrefour ibri regional grand plaza", c: "grocery, general, electronics", u: "https://www.carrefouroman.com", a: "" },
  { id: 265, n: "sharaf dg ibri digital appliance", c: "electronics", u: "https://oman.sharafdg.com", a: "" },
  { id: 266, n: "extra ibri telecom gadget shop", c: "electronics", u: "https://www.extra.com/en-om", a: "" },
  { id: 267, n: "e-max ibri home smart electronics", c: "electronics", u: "https://www.landmarkgroup.com", a: "" },
  { id: 268, n: "mi store ibri android mobile network", c: "electronics", u: "https://www.mi.com/om", a: "" },
  { id: 269, n: "virgin megastore ibri entertainment", c: "electronics, general", u: "https://www.virginmegastore.om", a: "" },
  { id: 270, n: "malabar gold and diamonds ibri shop", c: "fashion", u: "https://www.malabargoldanddiamonds.com", a: "" },

  // Part 11
  { id: 271, n: "joyalukkas jewellery ibri center", c: "fashion", u: "https://www.joyalukkas.com", a: "" },
  { id: 272, n: "kalyan jewellers ibri traditional", c: "fashion", u: "https://www.kalyanjewellers.net", a: "" },
  { id: 273, n: "centrepoint ibri lifestyle clothing", c: "fashion, general", u: "https://www.centrepointstores.com", a: "" },
  { id: 274, n: "max fashion ibri standard retail", c: "fashion", u: "https://www.maxfashion.com/om/en", a: "" },
  { id: 275, n: "splash ibri seasonal apparel store", c: "fashion", u: "https://www.splashfashions.com", a: "" },
  { id: 276, n: "h and m ibri budget friendly style", c: "fashion", u: "https://alshaya.com", a: "" },
  { id: 277, n: "zara ibri contemporary garment hub", c: "fashion", u: "https://www.zara.com/om", a: "" },
  { id: 278, n: "marks and spencer ibri premium food", c: "fashion, grocery", u: "https://www.marksandspencer.com/om", a: "" },
  { id: 279, n: "adidas ibri casual track clothes", c: "fashion", u: "https://www.adidas.com/om/en", a: "" },
  { id: 280, n: "nike ibri athletics clothing mall", c: "fashion", u: "https://www.nike.com/om", a: "" },
  { id: 281, n: "ikea ibri home decoration delivery", c: "general", u: "https://www.ikea.com/om/en", a: "" },
  { id: 282, n: "danube home ibri modern sanitary", c: "general", u: "https://danubehome.com/oman/en", a: "" },
  { id: 283, n: "home centre ibri premium furniture", c: "general", u: "https://www.homecentre.com", a: "" },
  { id: 284, n: "starbucks ibri town express cafe", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 285, n: "costa coffee ibri shopping plaza", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 286, n: "gloria jeans coffees ibri store", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 287, n: "caribou coffee ibri highway rest", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 288, n: "tim hortons ibri central plaza", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 289, n: "kfc ibri quick service meal order", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 290, n: "pizza hut ibri family combo dining", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 291, n: "burger king ibri retail food court", c: "general", u: "https://www.burgerking.om", a: "" },
  { id: 292, n: "hardees ibri premium beef restaurant", c: "general", u: "https://www.hardees.om", a: "" },
  { id: 293, n: "subway ibri casual custom salad", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 294, n: "baskin robbins ibri sundae corner", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 295, n: "dunkin ibri hot beverage station", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 296, n: "dominos pizza ibri fast delivery", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 297, n: "popeyes ibri tenders chicken shop", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 298, n: "texas chicken ibri online meal deal", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 299, n: "mcdonalds ibri highway dining", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 300, n: "asics ibri athletic runner shoe", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },

  // Part 12
  { id: 301, n: "puma ibri active lifestyle clothing", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 302, n: "reebok ibri classic sneakers shop", c: "fashion", u: "https://www.reebok.com.om", a: "" },
  { id: 303, n: "under armour ibri sports boutique", c: "fashion", u: "https://www.underarmour.ae", a: "" },
  { id: 304, n: "aldo shoes ibri premium accessory", c: "fashion", u: "https://www.aldoshoes.me/om/en", a: "" },
  { id: 305, n: "charles and keith ibri luxury shoe", c: "fashion", u: "https://www.charleskeith.com/om", a: "" },
  { id: 306, n: "dune london ibri formal leather", c: "fashion", u: "https://www.dunelondon.me/om/en", a: "" },
  { id: 307, n: "e-mart ibri grocery internet portal", c: "grocery, general", u: "https://www.emartoman.com", a: "" },
  { id: 308, n: "ourshopee ibri smart digital store", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 309, n: "ubuy ibri web cargo distribution", c: "general", u: "https://www.ubuy.om/en", a: "" },
  { id: 310, n: "desertcart ibri dynamic web trade", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 311, n: "namshi ibri apparel online delivery", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 312, n: "6thstreet ibri mobile catalog shop", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },
  { id: 313, n: "nestle pure life ibri bulk delivery", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 314, n: "lulu hypermarket buraimi mall", c: "grocery, general, electronics", u: "https://www.luluhypermarket.com", a: "" },
  { id: 315, n: "carrefour buraimi retail plaza", c: "grocery, general, electronics", u: "https://www.carrefouroman.com", a: "" },
  { id: 316, n: "sharaf dg buraimi appliance tech", c: "electronics", u: "https://oman.sharafdg.com", a: "" },
  { id: 317, n: "extra buraimi smart phone center", c: "electronics", u: "https://www.extra.com/en-om", a: "" },
  { id: 318, n: "e-max buraimi digital home center", c: "electronics", u: "https://www.landmarkgroup.com", a: "" },
  { id: 319, n: "mi store buraimi gadget showroom", c: "electronics", u: "https://www.mi.com/om", a: "" },
  { id: 320, n: "virgin megastore buraimi retail", c: "electronics, general", u: "https://www.virginmegastore.om", a: "" },
  { id: 321, n: "malabar gold and diamonds buraimi", c: "fashion", u: "https://www.malabargoldanddiamonds.com", a: "" },
  { id: 322, n: "joyalukkas jewellery buraimi shop", c: "fashion", u: "https://www.joyalukkas.com", a: "" },
  { id: 323, n: "kalyan jewellers buraimi traditional", c: "fashion", u: "https://www.kalyanjewellers.net", a: "" },
  { id: 324, n: "centrepoint buraimi clothing mall", c: "fashion, general", u: "https://www.centrepointstores.com", a: "" },
  { id: 325, n: "max fashion buraimi standard outlet", c: "fashion", u: "https://www.maxfashion.com/om/en", a: "" },
  { id: 326, n: "splash buraimi family apparel shop", c: "fashion", u: "https://www.splashfashions.com", a: "" },
  { id: 327, n: "h and m buraimi budget wear plaza", c: "fashion", u: "https://alshaya.com", a: "" },
  { id: 328, n: "zara buraimi contemporary design", c: "fashion", u: "https://www.zara.com/om", a: "" },
  { id: 329, n: "marks and spencer buraimi retail", c: "fashion, grocery", u: "https://www.marksandspencer.com/om", a: "" },
  { id: 330, n: "adidas buraimi sports shoe store", c: "fashion", u: "https://www.adidas.com/om/en", a: "" },

  // Part 13
  { id: 331, n: "nike buraimi active track clothing", c: "fashion", u: "https://www.nike.com/om", a: "" },
  { id: 332, n: "ikea buraimi home solutions delivery", c: "general", u: "https://www.ikea.com/om/en", a: "" },
  { id: 333, n: "danube home buraimi furniture hub", c: "general", u: "https://danubehome.com/oman/en", a: "" },
  { id: 334, n: "home centre buraimi lifestyle decor", c: "general", u: "https://www.homecentre.com", a: "" },
  { id: 335, n: "starbucks buraimi border road cafe", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 336, n: "costa coffee buraimi retail plaza", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 337, n: "gloria jeans coffees buraimi hub", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 338, n: "caribou coffee buraimi city center", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 339, n: "tim hortons buraimi premium counter", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 340, n: "kfc buraimi fast food order online", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 341, n: "pizza hut buraimi delivery counter", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 342, n: "burger king buraimi plaza dining", c: "general", u: "https://www.burgerking.om", a: "" },
  { id: 343, n: "hardees buraimi charbroiled burger", c: "general", u: "https://www.hardees.om", a: "" },
  { id: 344, n: "subway buraimi fresh custom salad", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 345, n: "baskin robbins buraimi scoop shop", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 346, n: "dunkin buraimi donut coffee corner", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 347, n: "dominos pizza buraimi quick order", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 348, n: "popeyes buraimi crispy chicken", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 349, n: "texas chicken buraimi combo dynamic", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 350, n: "mcdonalds buraimi value meal center", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 351, n: "asics buraimi runner shoe boutique", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },
  { id: 352, n: "puma buraimi active garment center", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 353, n: "reebok buraimi sport shoe collection", c: "fashion", u: "https://www.reebok.com.om", a: "" },
  { id: 354, n: "under armour buraimi fitness gear", c: "fashion", u: "https://www.underarmour.ae", a: "" },
  { id: 355, n: "aldo shoes buraimi fashion leather", c: "fashion", u: "https://www.aldoshoes.me/om/en", a: "" },
  { id: 356, n: "charles and keith buraimi purse hub", c: "fashion", u: "https://www.charleskeith.com/om", a: "" },
  { id: 357, n: "dune london buraimi modern style", c: "fashion", u: "https://www.dunelondon.me/om/en", a: "" },
  { id: 358, n: "e-mart buraimi grocery network", c: "grocery, general", u: "https://www.emartoman.com", a: "" },
  { id: 359, n: "ourshopee buraimi online web deals", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 360, n: "ubuy buraimi delivery internet", c: "general", u: "https://www.ubuy.om/en", a: "" },

  // Part 14
  { id: 361, n: "desertcart buraimi web logistics", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 362, n: "namshi buraimi fashion apparel app", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 363, n: "6thstreet buraimi clothing portal", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },
  { id: 364, n: "nestle pure life buraimi supply", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 365, n: "lulu hypermarket ibra regional plaza", c: "grocery, general, electronics", u: "https://www.luluhypermarket.com", a: "" },
  { id: 366, n: "carrefour ibra center retail market", c: "grocery, general, electronics", u: "https://www.carrefouroman.com", a: "" },
  { id: 367, n: "sharaf dg ibri appliance store shop", c: "electronics", u: "https://oman.sharafdg.com", a: "" },
  { id: 368, n: "extra ibra smart electronics boutique", c: "electronics", u: "https://www.extra.com/en-om", a: "" },
  { id: 369, n: "e-max ibra home gadget network", c: "electronics", u: "https://www.landmarkgroup.com", a: "" },
  { id: 370, n: "mi store ibra mobile digital center", c: "electronics", u: "https://www.mi.com/om", a: "" },
  { id: 371, n: "virgin megastore ibra media outlet", c: "electronics, general", u: "https://www.virginmegastore.om", a: "" },
  { id: 372, n: "malabar gold and diamonds ibra mall", c: "fashion", u: "https://www.malabargoldanddiamonds.com", a: "" },
  { id: 373, n: "joyalukkas jewellery ibra center hub", c: "fashion", u: "https://www.joyalukkas.com", a: "" },
  { id: 374, n: "kalyan jewellers ibra traditional bazaar", c: "fashion", u: "https://www.kalyanjewellers.net", a: "" },
  { id: 375, n: "centrepoint ibra lifestyle department", c: "fashion, general", u: "https://www.centrepointstores.com", a: "" },
  { id: 376, n: "max fashion ibra family discount clothes", c: "fashion", u: "https://www.maxfashion.com/om/en", a: "" },
  { id: 377, n: "splash ibra contemporary garments shop", c: "fashion", u: "https://www.splashfashions.com", a: "" },
  { id: 378, n: "h and m ibri budget friendly garment", c: "fashion", u: "https://alshaya.com", a: "" },
  { id: 379, n: "zara ibra fashion trends clothing", c: "fashion", u: "https://www.zara.com/om", a: "" },
  { id: 380, n: "marks and spencer ibra luxury food", c: "fashion, grocery", u: "https://www.marksandspencer.com/om", a: "" },
  { id: 381, n: "adidas ibra athletic apparel plaza", c: "fashion", u: "https://www.adidas.com/om/en", a: "" },
  { id: 382, n: "nike ibra professional running gear", c: "fashion", u: "https://www.nike.com/om", a: "" },
  { id: 383, n: "ikea ibra home furniture solutions", c: "general", u: "https://www.ikea.com/om/en", a: "" },
  { id: 384, n: "danube home ibra design living store", c: "general", u: "https://danubehome.com/oman/en", a: "" },
  { id: 385, n: "home centre ibra premium bedroom decor", c: "general", u: "https://www.homecentre.com", a: "" },
  { id: 386, n: "starbucks ibra highway express cafe", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 387, n: "costa coffee ibra market plaza counter", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 388, n: "gloria jeans coffees ibra town center", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 389, n: "caribou coffee ibra premium espresso", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 390, n: "tim hortons ibra local square booth", c: "general", u: "https://timhortonsme.com", a: "" },

  // Part 15
  { id: 391, n: "nestle pure life ibra", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 392, n: "starbucks ibra online coffee", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 393, n: "costa coffee ibra delivery", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 394, n: "gloria jeans coffees ibra shop", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 395, n: "caribou coffee ibra store", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 396, n: "tim hortons ibra plaza", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 397, n: "kfc ibra online food order", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 398, n: "pizza hut ibra delivery store", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 399, n: "burger king ibra retail shop", c: "general", u: "https://www.burgerking.om", a: "" },
  { id: 400, n: "hardees ibra restaurant", c: "general", u: "https://www.hardees.om", a: "" },
  { id: 401, n: "subway ibra online shop", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 402, n: "baskin robbins ibra icecream", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 403, n: "dunkin ibra coffee store", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 404, n: "dominos pizza ibra web shop", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 405, n: "popeyes ibra chicken store", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 406, n: "texas chicken ibra food court", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 407, n: "mcdonalds ibra hypermarket", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 408, n: "asics ibra running footwear", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },
  { id: 409, n: "puma ibra sportswear mall", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 410, n: "reebok ibra sneakers online", c: "fashion", u: "https://www.reebok.com.om", a: "" },
  { id: 411, n: "under armour ibra sport store", c: "fashion", u: "https://www.underarmour.ae", a: "" },
  { id: 412, n: "aldo shoes ibra shopping plaza", c: "fashion", u: "https://www.aldoshoes.me/om/en", a: "" },
  { id: 413, n: "charles and keith ibra footwear", c: "fashion", u: "https://www.charleskeith.com/om", a: "" },
  { id: 414, n: "dune london ibra retail mall", c: "fashion", u: "https://www.dunelondon.me/om/en", a: "" },
  { id: 415, n: "e-mart ibra grocery center", c: "grocery, general", u: "https://www.emartoman.com", a: "" },
  { id: 416, n: "ourshopee ibra online shopping", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 417, n: "ubuy ibra delivery service", c: "general", u: "https://www.ubuy.om/en", a: "" },
  { id: 418, n: "desertcart ibra internet store", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 419, n: "namshi ibra fashion online", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 420, n: "6thstreet ibra clothing app", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },

  // Part 16
  { id: 421, n: "nestle pure life rustaq", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 422, n: "starbucks rustaq online coffee", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 423, n: "costa coffee rustaq delivery", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 424, n: "gloria jeans coffees rustaq store", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 425, n: "caribou coffee rustaq center", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 426, n: "tim hortons rustaq mall", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 427, n: "kfc rustaq online food order", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 428, n: "pizza hut rustaq delivery store", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 429, n: "burger king rustaq market retail", c: "general", u: "https://www.burgerking.om", a: "" },
  { id: 430, n: "hardees rustaq fast food", c: "general", u: "https://www.hardees.om", a: "" },
  { id: 431, n: "subway rustaq online delivery", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 432, n: "baskin robbins rustaq icecream", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 433, n: "dunkin rustaq coffee plaza", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 434, n: "dominos pizza rustaq web shop", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 435, n: "popeyes rustaq chicken restaurant", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 436, n: "texas chicken rustaq food court", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 437, n: "mcdonalds rustaq hypermarket", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 438, n: "asics rustaq sports footwear", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },
  { id: 439, n: "puma rustaq clothing store", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 440, n: "reebok rustaq sneakers online", c: "fashion", u: "https://www.reebok.com.om", a: "" },
  { id: 441, n: "under armour rustaq athletic shop", c: "fashion", u: "https://www.underarmour.ae", a: "" },
  { id: 442, n: "aldo shoes rustaq shopping plaza", c: "fashion", u: "https://www.aldoshoes.me/om/en", a: "" },
  { id: 443, n: "charles and keith rustaq footwear", c: "fashion", u: "https://www.charleskeith.com/om", a: "" },
  { id: 444, n: "dune london rustaq retail mall", c: "fashion", u: "https://www.dunelondon.me/om/en", a: "" },
  { id: 445, n: "e-mart rustaq grocery network", c: "grocery, general", u: "https://www.emartoman.com", a: "" },
  { id: 446, n: "ourshopee rustaq online digital", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 447, n: "ubuy rustaq delivery web", c: "general", u: "https://www.ubuy.om/en", a: "" },
  { id: 448, n: "desertcart rustaq logistics store", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 449, n: "namshi rustaq boutique clothes", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 450, n: "6thstreet rustaq fashion mobile", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },

  // Part 17
  { id: 451, n: "nestle pure life barka", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 452, n: "starbucks barka online coffee", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 453, n: "costa coffee barka delivery", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 454, n: "gloria jeans coffees barka mall", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 455, n: "caribou coffee barka store", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 456, n: "tim hortons barka grand centre", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 457, n: "kfc barka online food delivery", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 458, n: "pizza hut barka delivery shop", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 459, n: "burger king barka retail center", c: "general", u: "https://www.burgerking.om", a: "" },
  { id: 460, n: "hardees barka fast food shop", c: "general", u: "https://www.hardees.om", a: "" },
  { id: 461, n: "subway barka online order store", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 462, n: "baskin robbins barka icecream", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 463, n: "dunkin barka coffee center", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 464, n: "dominos pizza barka web order", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 465, n: "popeyes barka crispy chicken", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 466, n: "texas chicken barka food court", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 467, n: "mcdonalds barka hypermarket shop", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 468, n: "asics barka sports footwear", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },
  { id: 469, n: "puma barka sportswear mall", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 470, n: "reebok barka sneakers online", c: "fashion", u: "https://www.reebok.com.om", a: "" },
  { id: 471, n: "under armour barka sport store", c: "fashion", u: "https://www.underarmour.ae", a: "" },
  { id: 472, n: "aldo shoes barka grand centre", c: "fashion", u: "https://www.aldoshoes.me/om/en", a: "" },
  { id: 473, n: "charles and keith barka footwear", c: "fashion", u: "https://www.charleskeith.com/om", a: "" },
  { id: 474, n: "dune london barka retail mall", c: "fashion", u: "https://www.dunelondon.me/om/en", a: "" },
  { id: 475, n: "e-mart barka grocery center", c: "grocery, general", u: "https://www.emartoman.com", a: "" },
  { id: 476, n: "ourshopee barka online deals", c: "general, electronics", u: "https://www.ourshopee.com/oman", a: "" },
  { id: 477, n: "ubuy barka delivery service", c: "general", u: "https://www.ubuy.om/en", a: "" },
  { id: 478, n: "desertcart barka internet store", c: "general", u: "https://oman.desertcart.com", a: "" },
  { id: 479, n: "namshi barka fashion online", c: "fashion, beauty", u: "https://www.namshi.com/oman-en", a: "" },
  { id: 480, n: "6thstreet barka clothing app", c: "fashion", u: "https://en-om.6thstreet.com", a: "" },

  // Part 18
  { id: 481, n: "nestle pure life musannah", c: "general, grocery", u: "https://www.nestlepurelife.com/om", a: "" },
  { id: 482, n: "starbucks musannah online coffee", c: "general", u: "https://www.starbucks.om", a: "" },
  { id: 483, n: "costa coffee musannah delivery", c: "general", u: "https://www.costacoffee.ae", a: "" },
  { id: 484, n: "gloria jeans coffees musannah shop", c: "general", u: "https://gloriajeanscoffees.com", a: "" },
  { id: 485, n: "caribou coffee musannah store", c: "general", u: "https://www.cariboucoffee.com", a: "" },
  { id: 486, n: "tim hortons musannah plaza", c: "general", u: "https://timhortonsme.com", a: "" },
  { id: 487, n: "kfc musannah online food order", c: "general", u: "https://www.oman.kfc.me", a: "" },
  { id: 488, n: "pizza hut musannah delivery store", c: "general", u: "https://www.pizzahut.om", a: "" },
  { id: 489, n: "burger king musannah retail shop", c: "general", u: "https://www.burgerking.om", a: "" },
  { id: 490, n: "hardees musannah restaurant", c: "general", u: "https://www.hardees.om", a: "" },
  { id: 491, n: "subway musannah online shop", c: "general", u: "https://www.subway.com/en-om", a: "" },
  { id: 492, n: "baskin robbins musannah icecream", c: "general", u: "https://www.baskinrobbins.com.om", a: "" },
  { id: 493, n: "dunkin musannah coffee store", c: "general", u: "https://www.dunkinoman.com", a: "" },
  { id: 494, n: "dominos pizza musannah web shop", c: "general", u: "https://www.dominos.om", a: "" },
  { id: 495, n: "popeyes musannah chicken store", c: "general", u: "https://www.popeyes.com", a: "" },
  { id: 496, n: "texas chicken musannah food court", c: "general", u: "https://www.texaschicken.com", a: "" },
  { id: 497, n: "mcdonalds musannah hypermarket", c: "general", u: "https://www.mcdonalds.com/om", a: "" },
  { id: 498, n: "asics musannah running footwear", c: "fashion", u: "https://www.asics.com/om/en-om", a: "" },
  { id: 499, n: "puma musannah sportswear mall", c: "fashion", u: "https://ae.puma.com/om/en", a: "" },
  { id: 500, n: "reebok musannah sneakers online", c: "fashion", u: "https://www.reebok.com.om", a: "" }
];

export default omanShops;
