 countryShops.qatar = [
  { id: 1, n: "1click laundry", c: "others", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 2, n: "24 cart", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 3, n: "6thstreet", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 4, n: "abc tiles online", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 5, n: "abdulhafiz group", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 6, n: "acon holidays", c: "others", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 7, n: "addony beauty", c: "beauty", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 8, n: "akly", c: "food delivery", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 9, n: "al anees", c: "electronics", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 10, n: "al-azizia boutique hotel", c: "others", u: "https://ecommerce.gov.qa/directory/", a: "" },

  { id: 11, n: "al-jameel showroom", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 12, n: "al majed perfumes", c: "beauty", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 13, n: "amazon qatar", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 14, n: "apple qatar", c: "electronics", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 15, n: "atlas book store", c: "books", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 16, n: "baby shop qatar", c: "clothing", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 17, n: "baladna", c: "food products", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 18, n: "balsam medical", c: "healthcare", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 19, n: "bata", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 20, n: "beauty booth qatar", c: "beauty", u: "https://ecommerce.gov.qa/directory/", a: "" },

  { id: 21, n: "beautyspot", c: "beauty", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 22, n: "belaoryx", c: "beauty", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 23, n: "berluti", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 24, n: "bigtree", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 25, n: "billjumla", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 26, n: "biovea", c: "healthcare", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 27, n: "black tulip flowers", c: "gifts", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 28, n: "bleems", c: "gifts", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 29, n: "blue diamond", c: "others", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 30, n: "blue lynx", c: "electronics", u: "https://ecommerce.gov.qa/directory/", a: "" },

  { id: 31, n: "blue salon", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 32, n: "bo ta ny", c: "beauty", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 33, n: "boconcept", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 34, n: "bon roastery", c: "others", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 35, n: "brandatt.com", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 36, n: "brands outlet", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 37, n: "bright horizon", c: "toys and sports", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 38, n: "bronze", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 39, n: "care n cure", c: "healthcare", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 40, n: "carrefour qatar", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },

  { id: 41, n: "city center online", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 42, n: "coffee shop qatar", c: "others", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 43, n: "computer plaza", c: "electronics", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 44, n: "daiso qatar", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 45, n: "doha pharmacy", c: "healthcare", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 46, n: "electronics home", c: "electronics", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 47, n: "fashion house qatar", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 48, n: "flower house", c: "gifts", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 49, n: "food palace", c: "food products", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 50, n: "gadget world", c: "electronics", u: "https://ecommerce.gov.qa/directory/", a: "" },

  { id: 51, n: "gift corner", c: "gifts", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 52, n: "green life", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 53, n: "guardian qatar", c: "healthcare", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 54, n: "harvey nichols", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 55, n: "healthy home", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 56, n: "home center", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 57, n: "home delivery", c: "food products", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 58, n: "ikea qatar", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 59, n: "in-q", c: "gifts", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 60, n: "inovo store", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },

  { id: 61, n: "invern", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 62, n: "j diamond q", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 63, n: "jaqar", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 64, n: "kids zone", c: "toys and sports", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 65, n: "lulu hypermarket qatar", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 66, n: "marina home", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 67, n: "medcare", c: "healthcare", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 68, n: "microsoft qatar", c: "electronics", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 69, n: "mobile store qatar", c: "electronics", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 70, n: "mothercare qatar", c: "clothing", u: "https://ecommerce.gov.qa/directory/", a: "" },

  { id: 71, n: "muji qatar", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 72, n: "nehmeh", c: "industrial and scientific goods", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 73, n: "nedina", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 74, n: "new balance qatar", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 75, n: "nology store", c: "electronics", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 76, n: "noon qatar", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 77, n: "novo cinema", c: "entertainment", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 78, n: "only roses", c: "gifts", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 79, n: "onomoo", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 80, n: "ooredoo", c: "electronics", u: "https://ecommerce.gov.qa/directory/", a: "" },

  { id: 81, n: "harvey nichols qatar", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 82, n: "home center qatar", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 83, n: "beauty outlet", c: "beauty", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 84, n: "perfume house", c: "beauty", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 85, n: "sport zone", c: "toys and sports", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 86, n: "toy store qatar", c: "toys and sports", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 87, n: "office supplies qatar", c: "others", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 88, n: "book store qatar", c: "books", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 89, n: "jewelry house", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 90, n: "lifestyle qatar", c: "marketplace", u: "https://ecommerce.gov.qa/directory/", a: "" },

  { id: 91, n: "restaurant delivery qatar", c: "food delivery", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 92, n: "grocery online qatar", c: "food products", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 93, n: "furniture shop qatar", c: "home and kitchen", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 94, n: "salon qatar", c: "beauty", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 95, n: "gift shop qatar", c: "gifts", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 96, n: "kids fashion qatar", c: "clothing", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 97, n: "men fashion qatar", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 98, n: "women fashion qatar", c: "fashion", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 99, n: "online tickets qatar", c: "entertainment", u: "https://ecommerce.gov.qa/directory/", a: "" },
  { id: 100, n: "payment gateway qatar", c: "others", u: "https://ecommerce.gov.qa/directory/", a: "" }
];
