countryShops.qatar = [
  { id: 1, n: "al meera consumer goods", c: "supermarket", u: "https://www.almeera.com.qa", a: "" },
  { id: 2, n: "monoprix qatar", c: "supermarket", u: "https://www.monoprix.qa", a: "" },
  { id: 3, n: "carrefour qatar", c: "supermarket", u: "https://www.carrefourqatar.com", a: "" },
  { id: 4, n: "lulu hypermarket", c: "supermarket", u: "https://www.luluhypermarket.com", a: "" },
  { id: 5, n: "family food centre", c: "supermarket", u: "https://www.ffcqatar.com", a: "" },
  { id: 6, n: "safari hypermarket", c: "supermarket", u: "https://www.safarihypermarket.com", a: "" },
  { id: 7, n: "grand hyper", c: "supermarket", u: "https://www.grandhyper.com", a: "" },
  { id: 8, n: "doha festival city", c: "mall", u: "https://www.dohafestivalcity.com", a: "" },
  { id: 9, n: "villaggio mall", c: "mall", u: "https://www.villaggioqatar.com", a: "" },
  { id: 10, n: "mall of qatar", c: "mall", u: "https://www.mallofqatar.com.qa", a: "" },
  { id: 11, n: "city center doha", c: "mall", u: "https://citycenterdoha.com", a: "" },
  { id: 12, n: "land mark mall", c: "mall", u: "https://landmarkdoha.com", a: "" },
  { id: 13, n: "starbucks qatar", c: "cafe", u: "https://www.starbucks.qa", a: "" },
  { id: 14, n: "tim hortons qatar", c: "cafe", u: "https://www.timhortons.com", a: "" },
  { id: 15, n: "caribou coffee", c: "cafe", u: "https://www.cariboucoffee.com", a: "" },
  { id: 16, n: "costa coffee qatar", c: "cafe", u: "https://www.costacoffee.com", a: "" },
  { id: 17, n: "shater abbas", c: "restaurant", u: "https://shaterabbas.com", a: "" },
  { id: 18, n: "kfc qatar", c: "restaurant", u: "https://www.kfc.me", a: "" },
  { id: 19, n: "pizza hut qatar", c: "restaurant", u: "https://www.pizzahut.qa", a: "" },
  { id: 20, n: "dominos pizza", c: "restaurant", u: "https://www.dominos.com.qa", a: "" },
  { id: 21, n: "hardees qatar", c: "restaurant", u: "https://www.hardees.qa", a: "" },
  { id: 22, n: "burger king qatar", c: "restaurant", u: "https://www.burgerking.qa", a: "" },
  { id: 23, n: "subway qatar", c: "restaurant", u: "https://www.subway.com", a: "" },
  { id: 24, n: "mcdonalds qatar", c: "restaurant", u: "https://www.mcdonalds.com", a: "" },
  { id: 25, n: "baskin robbins", c: "dessert", u: "https://www.baskinrobbins.com", a: "" },
  { id: 26, n: "dunkin qatar", c: "dessert", u: "https://www.dunkin.qa", a: "" },
  { id: 27, n: "jarir bookstore", c: "stationery", u: "https://www.jarir.com", a: "" },
  { id: 28, n: "virgin megastore", c: "electronics", u: "https://www.virginmegastore.qa", a: "" },
  { id: 29, n: "extra qatar", c: "electronics", u: "https://www.extra.com", a: "" },
  { id: 30, n: "e-max qatar", c: "electronics", u: "https://www.emaxme.com", a: "" },



  { id: 31, n: "al jazeera perfume", c: "fragrances", u: "https://aljazeeraperfumes.com", a: "" },
  { id: 32, n: "ajmal perfumes", c: "fragrances", u: "https://ajmalperfume.com", a: "" },
  { id: 33, n: "rasasi perfumes", c: "fragrances", u: "https://rasasi.com", a: "" },
  { id: 34, n: "ansar gallery", c: "department store", u: "https://ansargallery.com", a: "" },
  { id: 35, n: "ramez shopping center", c: "department store", u: "https://ramez.net", a: "" },
  { id: 36, n: "max fashion", c: "clothing", u: "https://www.maxfashion.com", a: "" },
  { id: 37, n: "lifestyle qatar", c: "home decor", u: "https://lifestyleshops.com", a: "" },
  { id: 38, n: "home centre", c: "furniture", u: "https://www.homecentre.com", a: "" },
  { id: 39, n: "ikea qatar", c: "furniture", u: "https://www.ikea.com/qa", a: "" },
  { id: 40, n: "centrepoint qatar", c: "fashion", u: "https://www.centrepointstores.com", a: "" },
  { id: 41, n: "sephora qatar", c: "cosmetics", u: "https://www.sephora.qa", a: "" },
  { id: 42, n: "bath and body works", c: "cosmetics", u: "https://www.bathandbodyworks.com.qa", a: "" },
  { id: 43, n: "boots pharmacy", c: "pharmacy", u: "https://me.boots.com", a: "" },
  { id: 44, n: "pharmacy 1", c: "pharmacy", u: "https://pharmacy1.net", a: "" },
  { id: 45, n: "al jaber opticians", c: "optics", u: "https://aljaberopticians.com", a: "" },
  { id: 46, n: "magrabi optical", c: "optics", u: "https://magrabi.com", a: "" },
  { id: 47, n: "techno blue", c: "electronics", u: "https://technoblue.com.qa", a: "" },
  { id: 48, n: "starlink qatar", c: "electronics", u: "https://starlink.qa", a: "" },
  { id: 49, n: "al naqeeb optics", c: "optics", u: "https://alnaqeeboptics.com", a: "" },
  { id: 50, n: "gulf colours", c: "photography", u: "https://gulfcolours.com", a: "" },
  { id: 51, n: "qatar airways duty free", c: "shopping", u: "https://www.qatardutyfree.com", a: "" },
  { id: 52, n: "al mana jewelry", c: "jewelry", u: "https://almanajewellery.com", a: "" },
  { id: 53, n: "damas jewellery", c: "jewelry", u: "https://damasjewellery.com", a: "" },
  { id: 54, n: "joyalukkas qatar", c: "jewelry", u: "https://joyalukkas.qa", a: "" },
  { id: 55, n: "malabar gold and diamonds", c: "jewelry", u: "https://malabargoldanddiamonds.com", a: "" },
  { id: 56, n: "sky jewellery", c: "jewelry", u: "https://skyjewellery.com", a: "" },
  { id: 57, n: "blue salon", c: "luxury fashion", u: "https://bluesalon.com", a: "" },
  { id: 58, n: "paris gallery", c: "luxury fashion", u: "https://parisgallery.com", a: "" },
  { id: 59, n: "al tawasol", c: "supermarket", u: "https://altawasol.com", a: "" },
  { id: 60, n: "k-mart qatar", c: "supermarket", u: "https://kmart.qa", a: "" },


  { id: 61, n: "al rawabi food center", c: "supermarket", u: "https://alrawabigroup.com", a: "" },
  { id: 62, n: "safa hypermarket", c: "supermarket", u: "https://safahypermarket.com", a: "" },
  { id: 63, n: "new indian supermarket", c: "supermarket", u: "https://newindiansupermarket.com", a: "" },
  { id: 64, n: "my choice hypermarket", c: "supermarket", u: "https://mychoice.qa", a: "" },
  { id: 65, n: "al rayyan hypermarket", c: "supermarket", u: "https://alrayyan.qa", a: "" },
  { id: 66, n: "doha city hypermarket", c: "supermarket", u: "https://dohacityhyper.qa", a: "" },
  { id: 67, n: "q-mart", c: "supermarket", u: "https://qmart.qa", a: "" },
  { id: 68, n: "al muna supermarket", c: "supermarket", u: "https://almunagroup.com", a: "" },
  { id: 69, n: "doha oasis mall", c: "mall", u: "https://dohaoasis.qa", a: "" },
  { id: 70, n: "tawar mall", c: "mall", u: "https://tawarmall.qa", a: "" },
  { id: 71, n: "ezdan mall", c: "mall", u: "https://ezdanmall.qa", a: "" },
  { id: 72, n: "mirqab mall", c: "mall", u: "https://mirqabmall.com", a: "" },
  { id: 73, n: "gulf mall", c: "mall", u: "https://gulfmallqatar.com", a: "" },
  { id: 74, n: "dar al salam mall", c: "mall", u: "https://daralsalammall.com", a: "" },
  { id: 75, n: "b square mall", c: "mall", u: "https://bsquaremall.com", a: "" },
  { id: 76, n: "the pearl qatar retail", c: "mall", u: "https://thepearlqatar.com", a: "" },
  { id: 77, n: "halo cafe", c: "cafe", u: "https://halocafe.qa", a: "" },
  { id: 78, n: "flat white specialty coffee", c: "cafe", u: "https://flatwhite.qa", a: "" },
  { id: 79, n: "w cafe", c: "cafe", u: "https://w-doha.com", a: "" },
  { id: 80, n: "café 42", c: "cafe", u: "https://cafe42.qa", a: "" },
  { id: 81, n: "zaatar w zeit", c: "restaurant", u: "https://zaatarwzeit.net", a: "" },
  { id: 82, n: "applebee's qatar", c: "restaurant", u: "https://applebees.qa", a: "" },
  { id: 83, n: "p.f. chang's qatar", c: "restaurant", u: "https://pfchangs.com", a: "" },
  { id: 84, n: "nando's qatar", c: "restaurant", u: "https://nandos.qa", a: "" },
  { id: 85, n: "texas roadhouse qatar", c: "restaurant", u: "https://texasroadhouse.com", a: "" },
  { id: 86, n: "shake shack qatar", c: "restaurant", u: "https://shakeshack.qa", a: "" },
  { id: 87, n: "mag bakery", c: "bakery", u: "https://magbakery.qa", a: "" },
  { id: 88, n: "doha sweets", c: "bakery", u: "https://dohasweets.com", a: "" },
  { id: 89, n: "al amira sweets", c: "bakery", u: "https://alamirasweets.qa", a: "" },
  { id: 90, n: "karak mquanes", c: "cafe", u: "https://karakmquanes.qa", a: "" },


  
  { id: 91, n: "gourmet gulf", c: "food service", u: "https://gourmetgulf.com", a: "" },
  { id: 92, n: "al bake", c: "bakery", u: "https://albake.qa", a: "" },
  { id: 93, n: "saadeddin pastry", c: "bakery", u: "https://saadeddin.com", a: "" },
  { id: 94, n: "al mandarine", c: "bakery", u: "https://almandarine.com", a: "" },
  { id: 95, n: "l'eto caffe", c: "cafe", u: "https://letocaffe.qa", a: "" },
  { id: 96, n: "espresso lab", c: "cafe", u: "https://espressolab.qa", a: "" },
  { id: 97, n: "percentage specialty coffee", c: "cafe", u: "https://percentage.qa", a: "" },
  { id: 98, n: "viva cafe", c: "cafe", u: "https://vivacafe.qa", a: "" },
  { id: 99, n: "shake it", c: "beverages", u: "https://shakeit.qa", a: "" },
  { id: 100, n: "juicery", c: "beverages", u: "https://juicery.qa", a: "" },
  { id: 101, n: "al jaber watch", c: "watches", u: "https://aljaberwatches.com", a: "" },
  { id: 102, n: "rivoli shop", c: "watches", u: "https://rivoligroup.com", a: "" },
  { id: 103, n: "hour choice", c: "watches", u: "https://hourchoice.com", a: "" },
  { id: 104, n: "aldo accessories", c: "fashion", u: "https://aldoshoes.com.qa", a: "" },
  { id: 105, n: "charles and keith", c: "fashion", u: "https://charleskeith.com/qa", a: "" },
  { id: 106, n: "bath and body works", c: "personal care", u: "https://bathandbodyworks.com.qa", a: "" },
  { id: 107, n: "the body shop", c: "personal care", u: "https://thebodyshop.qa", a: "" },
  { id: 108, n: "loccitane qatar", c: "cosmetics", u: "https://loccitane.qa", a: "" },
  { id: 109, n: "faces qatar", c: "cosmetics", u: "https://faces.com/qa", a: "" },
  { id: 110, n: "ajmal", c: "fragrances", u: "https://ajmalperfume.com", a: "" },
  { id: 111, n: "arabian oud", c: "fragrances", u: "https://arabianoud.com", a: "" },
  { id: 112, n: "gant qatar", c: "fashion", u: "https://gant.com", a: "" },
  { id: 113, n: "tommy hilfiger", c: "fashion", u: "https://tommy.com", a: "" },
  { id: 114, n: "polo ralph lauren", c: "fashion", u: "https://ralphlauren.com", a: "" },
  { id: 115, n: "timberland", c: "fashion", u: "https://timberland.com", a: "" },
  { id: 116, n: "nike store", c: "sportswear", u: "https://nike.com", a: "" },
  { id: 117, n: "adidas store", c: "sportswear", u: "https://adidas.com", a: "" },
  { id: 118, n: "puma store", c: "sportswear", u: "https://puma.com", a: "" },
  { id: 119, n: "under armour", c: "sportswear", u: "https://underarmour.qa", a: "" },
  { id: 120, n: "go sport", c: "sportswear", u: "https://gosportme.com", a: "" },



  { id: 121, n: "al jaber optics", c: "optics", u: "https://aljaberopticians.com", a: "" },
  { id: 122, n: "yateem opticians", c: "optics", u: "https://yateemoptician.com", a: "" },
  { id: 123, n: "magrabi optical", c: "optics", u: "https://magrabi.com", a: "" },
  { id: 124, n: "optica", c: "optics", u: "https://optica.net", a: "" },
  { id: 125, n: "qatar optical", c: "optics", u: "https://qataroptical.qa", a: "" },
  { id: 126, n: "damas jewellery", c: "jewelry", u: "https://damasjewellery.com", a: "" },
  { id: 127, n: "joyalukkas qatar", c: "jewelry", u: "https://joyalukkas.qa", a: "" },
  { id: 128, n: "malabar gold and diamonds", c: "jewelry", u: "https://malabargoldanddiamonds.com", a: "" },
  { id: 129, n: "sky jewellery", c: "jewelry", u: "https://skyjewellery.com", a: "" },
  { id: 130, n: "al fardan jewellery", c: "jewelry", u: "https://alfardanjewellery.com", a: "" },
  { id: 131, n: "atlas jewellery", c: "jewelry", u: "https://atlasjewellery.com", a: "" },
  { id: 132, n: "kalyan jewellers", c: "jewelry", u: "https://kalyanjewellers.net", a: "" },
  { id: 133, n: "damask", c: "furniture", u: "https://damask.qa", a: "" },
  { id: 134, n: "marina home interiors", c: "furniture", u: "https://marinahomeinteriors.com", a: "" },
  { id: 135, n: "west elm", c: "furniture", u: "https://westelm.me", a: "" },
  { id: 136, n: "pottery barn", c: "furniture", u: "https://potterybarn.me", a: "" },
  { id: 137, n: "crate and barrel", c: "furniture", u: "https://crateandbarrel.me", a: "" },
  { id: 138, n: "pan emirates", c: "furniture", u: "https://panemirates.com", a: "" },
  { id: 139, n: "h and m", c: "fashion", u: "https://hm.com/qa", a: "" },
  { id: 140, n: "zara", c: "fashion", u: "https://zara.com/qa", a: "" },
  { id: 141, n: "mango", c: "fashion", u: "https://shop.mango.com/qa", a: "" },
  { id: 142, n: "bershka", c: "fashion", u: "https://bershka.com/qa", a: "" },
  { id: 143, n: "pull and bear", c: "fashion", u: "https://pullandbear.com/qa", a: "" },
  { id: 144, n: "stradivarius", c: "fashion", u: "https://stradivarius.com/qa", a: "" },
  { id: 145, n: "massimo dutti", c: "fashion", u: "https://massimodutti.com/qa", a: "" },
  { id: 146, n: "next qatar", c: "fashion", u: "https://next.qa", a: "" },
  { id: 147, n: "marks and spencer", c: "fashion", u: "https://marksandspencer.com/qa", a: "" },
  { id: 148, n: "splash fashion", c: "fashion", u: "https://splashfashions.com", a: "" },
  { id: 149, n: "lc waikiki", c: "fashion", u: "https://lcwaikiki.qa", a: "" },
  { id: 150, n: "defacto", c: "fashion", u: "https://defacto.com/qa", a: "" },


  { id: 151, n: "redtag qatar", c: "fashion", u: "https://redtag-stores.com/qa", a: "" },
  { id: 152, n: "babyshop qatar", c: "kids fashion", u: "https://babyshopstores.com/qa", a: "" },
  { id: 153, n: "shoe mart", c: "footwear", u: "https://shoemartstores.com/qa", a: "" },
  { id: 154, n: "lifestyle", c: "home decor", u: "https://lifestyleshops.com/qa", a: "" },
  { id: 155, n: "home centre", c: "furniture", u: "https://homecentre.com/qa", a: "" },
  { id: 156, n: "splash", c: "fashion", u: "https://splashfashions.com/qa", a: "" },
  { id: 157, n: "max", c: "fashion", u: "https://maxfashion.com/qa", a: "" },
  { id: 158, n: "saco qatar", c: "hardware", u: "https://saco.sa/en/qatar", a: "" },
  { id: 159, n: "ace hardware", c: "hardware", u: "https://aceuae.com/qa", a: "" },
  { id: 160, n: "the one qatar", c: "furniture", u: "https://theone.com/qa", a: "" },
  { id: 161, n: "west elm qatar", c: "furniture", u: "https://westelm.me/en-qa", a: "" },
  { id: 162, n: "pottery barn kids", c: "furniture", u: "https://potterybarnkids.me/en-qa", a: "" },
  { id: 163, n: "muji qatar", c: "lifestyle", u: "https://muji.com/qa", a: "" },
  { id: 164, n: "ikea", c: "furniture", u: "https://ikea.com/qa", a: "" },
  { id: 165, n: "homes r us", c: "furniture", u: "https://homesrus.qa", a: "" },
  { id: 166, n: "lulu hypermarket", c: "supermarket", u: "https://luluhypermarket.com/en-qa", a: "" },
  { id: 167, n: "al meera", c: "supermarket", u: "https://almeera.com.qa", a: "" },
  { id: 168, n: "carrefour", c: "supermarket", u: "https://carrefourqatar.com", a: "" },
  { id: 169, n: "monoprix", c: "supermarket", u: "https://monoprix.qa", a: "" },
  { id: 170, n: "family food centre", c: "supermarket", u: "https://ffcqatar.com", a: "" },
  { id: 171, n: "safari hypermarket", c: "supermarket", u: "https://safarihypermarket.com", a: "" },
  { id: 172, n: "grand hyper", c: "supermarket", u: "https://grandhyper.com", a: "" },
  { id: 173, n: "nestos hypermarket", c: "supermarket", u: "https://nestogroup.com/qa", a: "" },
  { id: 174, n: "new indian supermarket", c: "supermarket", u: "https://newindiansupermarket.com", a: "" },
  { id: 175, n: "al rawabi food center", c: "supermarket", u: "https://alrawabigroup.com", a: "" },
  { id: 176, n: "safa hypermarket", c: "supermarket", u: "https://safahypermarket.com", a: "" },
  { id: 177, n: "q-mart", c: "supermarket", u: "https://qmart.qa", a: "" },
  { id: 178, n: "al rayyan hypermarket", c: "supermarket", u: "https://alrayyan.qa", a: "" },
  { id: 179, n: "my choice hypermarket", c: "supermarket", u: "https://mychoice.qa", a: "" },
  { id: 180, n: "doha city hypermarket", c: "supermarket", u: "https://dohacityhyper.qa", a: "" },


  { id: 181, n: "al jaber opticians", c: "optics", u: "https://aljaberopticians.com", a: "" },
  { id: 182, n: "magrabi optical", c: "optics", u: "https://magrabi.com", a: "" },
  { id: 183, n: "yateem opticians", c: "optics", u: "https://yateemoptician.com", a: "" },
  { id: 184, n: "optica", c: "optics", u: "https://optica.net", a: "" },
  { id: 185, n: "vision express", c: "optics", u: "https://visionexpress.me", a: "" },
  { id: 186, n: "al naqeeb optics", c: "optics", u: "https://alnaqeeboptics.com", a: "" },
  { id: 187, n: "qatar optical", c: "optics", u: "https://qataroptical.qa", a: "" },
  { id: 188, n: "al jazeera perfumes", c: "fragrances", u: "https://aljazeeraperfumes.com", a: "" },
  { id: 189, n: "ajmal perfumes", c: "fragrances", u: "https://ajmalperfume.com", a: "" },
  { id: 190, n: "rasasi perfumes", c: "fragrances", u: "https://rasasi.com", a: "" },
  { id: 191, n: "arabian oud", c: "fragrances", u: "https://arabianoud.com", a: "" },
  { id: 192, n: "asgharali perfumes", c: "fragrances", u: "https://asgharali.com", a: "" },
  { id: 193, n: "swiss arabian", c: "fragrances", u: "https://swissob.com", a: "" },
  { id: 194, n: "paris gallery", c: "luxury fashion", u: "https://parisgallery.com", a: "" },
  { id: 195, n: "blue salon", c: "luxury fashion", u: "https://bluesalon.com", a: "" },
  { id: 196, n: "fifty one east", c: "luxury fashion", u: "https://51east.qa", a: "" },
  { id: 197, n: "al mana jewelry", c: "jewelry", u: "https://almanajewellery.com", a: "" },
  { id: 198, n: "damas jewellery", c: "jewelry", u: "https://damasjewellery.com", a: "" },
  { id: 199, n: "joyalukkas qatar", c: "jewelry", u: "https://joyalukkas.qa", a: "" },
  { id: 200, n: "malabar gold and diamonds", c: "jewelry", u: "https://malabargoldanddiamonds.com", a: "" },
  { id: 201, n: "sky jewellery", c: "jewelry", u: "https://skyjewellery.com", a: "" },
  { id: 202, n: "atlas jewellery", c: "jewelry", u: "https://atlasjewellery.com", a: "" },
  { id: 203, n: "kalyan jewellers", c: "jewelry", u: "https://kalyanjewellers.net", a: "" },
  { id: 204, n: "al fardan jewellery", c: "jewelry", u: "https://alfardanjewellery.com", a: "" },
  { id: 205, n: "lamarque", c: "fashion", u: "https://lamarque.qa", a: "" },
  { id: 206, n: "aldo accessories", c: "fashion", u: "https://aldoshoes.com.qa", a: "" },
  { id: 207, n: "charles and keith", c: "fashion", u: "https://charleskeith.com/qa", a: "" },
  { id: 208, n: "aldo shoes", c: "footwear", u: "https://aldoshoes.com.qa", a: "" },
  { id: 209, n: "skechers qatar", c: "footwear", u: "https://skechers.qa", a: "" },
  { id: 210, n: "clarks qatar", c: "footwear", u: "https://clarks.com/en-qa", a: "" },

  
  { id: 211, n: "adidas qatar", c: "sportswear", u: "https://adidas.qa", a: "" },
  { id: 212, n: "nike qatar", c: "sportswear", u: "https://nike.qa", a: "" },
  { id: 213, n: "puma qatar", c: "sportswear", u: "https://puma.com/en-qa", a: "" },
  { id: 214, n: "under armour qatar", c: "sportswear", u: "https://underarmour.qa", a: "" },
  { id: 215, n: "reebok qatar", c: "sportswear", u: "https://reebok.qa", a: "" },
  { id: 216, n: "go sport qatar", c: "sportswear", u: "https://gosportme.com/qa", a: "" },
  { id: 217, n: "sun and sand sports", c: "sportswear", u: "https://en-qa.sssports.com", a: "" },
  { id: 218, n: "asics qatar", c: "sportswear", u: "https://asics.com/qa", a: "" },
  { id: 219, n: "new balance qatar", c: "sportswear", u: "https://newbalance.qa", a: "" },
  { id: 220, n: "decathlon qatar", c: "sportswear", u: "https://decathlon.qa", a: "" },
  { id: 221, n: "virgin megastore", c: "electronics", u: "https://virginmegastore.qa", a: "" },
  { id: 222, n: "jarir bookstore", c: "stationery", u: "https://jarir.com/qa", a: "" },
  { id: 223, n: "techno blue", c: "electronics", u: "https://technoblue.com.qa", a: "" },
  { id: 224, n: "starlink", c: "electronics", u: "https://starlink.qa", a: "" },
  { id: 225, n: "iSpot qatar", c: "electronics", u: "https://ispot.qa", a: "" },
  { id: 226, n: "al naqeeb optics", c: "optics", u: "https://alnaqeeboptics.com", a: "" },
  { id: 227, n: "gulf colours", c: "electronics", u: "https://gulfcolours.com", a: "" },
  { id: 228, n: "qatar airways duty free", c: "general", u: "https://qatardutyfree.com", a: "" },
  { id: 229, n: "kfc qatar", c: "restaurant", u: "https://qatar.kfc.me", a: "" },
  { id: 230, n: "pizza hut qatar", c: "restaurant", u: "https://pizzahut.qa", a: "" },
  { id: 231, n: "dominos pizza", c: "restaurant", u: "https://dominos.com.qa", a: "" },
  { id: 232, n: "hardees qatar", c: "restaurant", u: "https://hardees.qa", a: "" },
  { id: 233, n: "burger king qatar", c: "restaurant", u: "https://burgerking.qa", a: "" },
  { id: 234, n: "subway qatar", c: "restaurant", u: "https://subway.com/en-qa", a: "" },
  { id: 235, n: "mcdonalds qatar", c: "restaurant", u: "https://mcdonalds.com/qa", a: "" },
  { id: 236, n: "baskin robbins", c: "dessert", u: "https://baskinrobbins.qa", a: "" },
  { id: 237, n: "dunkin qatar", c: "dessert", u: "https://dunkin.qa", a: "" },
  { id: 238, n: "starbucks qatar", c: "cafe", u: "https://starbucks.qa", a: "" },
  { id: 239, n: "tim hortons qatar", c: "cafe", u: "https://timhortons.qa", a: "" },
  { id: 240, n: "caribou coffee", c: "cafe", u: "https://cariboucoffee.qa", a: "" },



  { id: 241, n: "zaatar w zeit", c: "restaurant", u: "https://zaatarwzeit.net", a: "" },
  { id: 242, n: "applebee's qatar", c: "restaurant", u: "https://applebees.qa", a: "" },
  { id: 243, n: "p.f. chang's qatar", c: "restaurant", u: "https://pfchangs.com/qa", a: "" },
  { id: 244, n: "nando's qatar", c: "restaurant", u: "https://nandos.qa", a: "" },
  { id: 245, n: "texas roadhouse qatar", c: "restaurant", u: "https://texasroadhouse.com/qa", a: "" },
  { id: 246, n: "shake shack qatar", c: "restaurant", u: "https://shakeshack.qa", a: "" },
  { id: 247, n: "friday's qatar", c: "restaurant", u: "https://fridays.qa", a: "" },
  { id: 248, n: "denny's qatar", c: "restaurant", u: "https://dennys.qa", a: "" },
  { id: 249, n: "ihop qatar", c: "restaurant", u: "https://ihop.qa", a: "" },
  { id: 250, n: "chili's qatar", c: "restaurant", u: "https://chilis.qa", a: "" },
  { id: 251, n: "mag bakery", c: "bakery", u: "https://magbakery.qa", a: "" },
  { id: 252, n: "doha sweets", c: "bakery", u: "https://dohasweets.com", a: "" },
  { id: 253, n: "al amira sweets", c: "bakery", u: "https://alamirasweets.qa", a: "" },
  { id: 254, n: "karak mquanes", c: "cafe", u: "https://karakmquanes.qa", a: "" },
  { id: 255, n: "halo cafe", c: "cafe", u: "https://halocafe.qa", a: "" },
  { id: 256, n: "flat white specialty coffee", c: "cafe", u: "https://flatwhite.qa", a: "" },
  { id: 257, n: "w cafe", c: "cafe", u: "https://w-doha.com/w-cafe", a: "" },
  { id: 258, n: "café 42", c: "cafe", u: "https://cafe42.qa", a: "" },
  { id: 259, n: "gourmet gulf", c: "food service", u: "https://gourmetgulf.com", a: "" },
  { id: 260, n: "al bake", c: "bakery", u: "https://albake.qa", a: "" },
  { id: 261, n: "saadeddin pastry", c: "bakery", u: "https://saadeddin.com", a: "" },
  { id: 262, n: "al mandarine", c: "bakery", u: "https://almandarine.com", a: "" },
  { id: 263, n: "l'eto caffe", c: "cafe", u: "https://letocaffe.qa", a: "" },
  { id: 264, n: "espresso lab", c: "cafe", u: "https://espressolab.qa", a: "" },
  { id: 265, n: "percentage specialty coffee", c: "cafe", u: "https://percentage.qa", a: "" },
  { id: 266, n: "viva cafe", c: "cafe", u: "https://vivacafe.qa", a: "" },
  { id: 267, n: "shake it", c: "beverages", u: "https://shakeit.qa", a: "" },
  { id: 268, n: "juicery", c: "beverages", u: "https://juicery.qa", a: "" },
  { id: 269, n: "al rawabi food center", c: "supermarket", u: "https://alrawabigroup.com", a: "" },
  { id: 270, n: "safa hypermarket", c: "supermarket", u: "https://safahypermarket.com", a: "" },


  

  { id: 271, n: "al muna supermarket", c: "supermarket", u: "https://almunagroup.com", a: "" },
  { id: 272, n: "doha oasis mall", c: "mall", u: "https://dohaoasis.qa", a: "" },
  { id: 273, n: "tawar mall", c: "mall", u: "https://tawarmall.qa", a: "" },
  { id: 274, n: "ezdan mall", c: "mall", u: "https://ezdanmall.qa", a: "" },
  { id: 275, n: "mirqab mall", c: "mall", u: "https://mirqabmall.com", a: "" },
  { id: 276, n: "gulf mall", c: "mall", u: "https://gulfmallqatar.com", a: "" },
  { id: 277, n: "dar al salam mall", c: "mall", u: "https://daralsalammall.com", a: "" },
  { id: 278, n: "b square mall", c: "mall", u: "https://bsquaremall.com", a: "" },
  { id: 279, n: "the pearl qatar retail", c: "mall", u: "https://thepearlqatar.com", a: "" },
  { id: 280, n: "city center doha", c: "mall", u: "https://citycenterdoha.com", a: "" },
  { id: 281, n: "landmark mall", c: "mall", u: "https://landmarkdoha.com", a: "" },
  { id: 282, n: "hyatt plaza", c: "mall", u: "https://hyattplaza.com", a: "" },
  { id: 283, n: "alkhor mall", c: "mall", u: "https://alkhormall.com", a: "" },
  { id: 284, n: "q-mall", c: "mall", u: "https://q-mall.qa", a: "" },
  { id: 285, n: "the gate mall", c: "mall", u: "https://thegatemall.com", a: "" },
  { id: 286, n: "lagoon mall", c: "mall", u: "https://lagoonmall.qa", a: "" },
  { id: 287, n: "vendome mall", c: "mall", u: "https://placevendomeqatar.com", a: "" },
  { id: 288, n: "royal plaza", c: "mall", u: "https://royalplaza.qa", a: "" },
  { id: 289, n: "century mall", c: "mall", u: "https://centurymall.qa", a: "" },
  { id: 290, n: "qatar mall", c: "mall", u: "https://mallofqatar.com.qa", a: "" },
  { id: 291, n: "al kout mall", c: "mall", u: "https://alkoutmall.com", a: "" },
  { id: 292, n: "avenues mall qatar", c: "mall", u: "https://theavenuesqatar.com", a: "" },
  { id: 293, n: "mall of qatar services", c: "services", u: "https://mallofqatar.com.qa", a: "" },
  { id: 294, n: "festival city services", c: "services", u: "https://dohafestivalcity.com", a: "" },
  { id: 295, n: "villaggio services", c: "services", u: "https://villaggioqatar.com", a: "" },
  { id: 296, n: "city center services", c: "services", u: "https://citycenterdoha.com", a: "" },
  { id: 297, n: "ezdan mall services", c: "services", u: "https://ezdanmall.qa", a: "" },
  { id: 298, n: "tawar mall services", c: "services", u: "https://tawarmall.qa", a: "" },
  { id: 299, n: "landmark services", c: "services", u: "https://landmarkdoha.com", a: "" },
  { id: 300, n: "gulf mall services", c: "services", u: "https://gulfmallqatar.com", a: "" },

  

  { id: 301, n: "al mulla plaza", c: "retail", u: "https://almullaplaza.qa", a: "" },
  { id: 302, n: "jumbo electronics", c: "electronics", u: "https://jumboqatar.com", a: "" },
  { id: 303, n: "pro tech", c: "electronics", u: "https://protech.qa", a: "" },
  { id: 304, n: "alif stores", c: "stationery", u: "https://alifstores.com", a: "" },
  { id: 305, n: "stationery world", c: "stationery", u: "https://stationeryworld.qa", a: "" },
  { id: 306, n: "paper moon", c: "gift shop", u: "https://papermoon.qa", a: "" },
  { id: 307, n: "whsmith qatar", c: "books", u: "https://whsmith.qa", a: "" },
  { id: 308, n: "house of bedding", c: "home", u: "https://houseofbedding.qa", a: "" },
  { id: 309, n: "sleep high", c: "home", u: "https://sleephigh.qa", a: "" },
  { id: 310, n: "royal furniture", c: "furniture", u: "https://royalfurniture.qa", a: "" },
  { id: 311, n: "al jaber watches", c: "jewelry", u: "https://aljaberwatches.com", a: "" },
  { id: 312, n: "orient pearl", c: "restaurant", u: "https://orientpearl.qa", a: "" },
  { id: 313, n: "parisa restaurant", c: "restaurant", u: "https://parisa.qa", a: "" },
  { id: 314, n: "shisha terrace", c: "cafe", u: "https://shishaterrace.qa", a: "" },
  { id: 315, n: "al nahda", c: "supermarket", u: "https://alnahda.qa", a: "" },
  { id: 316, n: "q-supermarket", c: "supermarket", u: "https://qsupermarket.qa", a: "" },
  { id: 317, n: "baker and spice", c: "bakery", u: "https://bakerandspice.com", a: "" },
  { id: 318, n: "la maison du chocolat", c: "dessert", u: "https://lamaisonduchocolat.qa", a: "" },
  { id: 319, n: "patchi qatar", c: "dessert", u: "https://patchi.com/qa", a: "" },
  { id: 320, n: "godiva qatar", c: "dessert", u: "https://godiva.qa", a: "" },
  { id: 321, n: "aldo fashion", c: "fashion", u: "https://aldoshoes.com.qa", a: "" },
  { id: 322, n: "call it spring", c: "fashion", u: "https://callitspring.qa", a: "" },
  { id: 323, n: "bershka qatar", c: "fashion", u: "https://bershka.com/qa", a: "" },
  { id: 324, n: "pull and bear qatar", c: "fashion", u: "https://pullandbear.com/qa", a: "" },
  { id: 325, n: "stradivarius qatar", c: "fashion", u: "https://stradivarius.com/qa", a: "" },
  { id: 326, n: "oysho qatar", c: "fashion", u: "https://oysho.com/qa", a: "" },
  { id: 327, n: "zara home", c: "home", u: "https://zarahome.com/qa", a: "" },
  { id: 328, n: "massimo dutti qatar", c: "fashion", u: "https://massimodutti.com/qa", a: "" },
  { id: 329, n: "mango qatar", c: "fashion", u: "https://shop.mango.com/qa", a: "" },
  { id: 330, n: "next qatar", c: "fashion", u: "https://next.qa", a: "" },




  { id: 331, n: "hm qatar", c: "fashion", u: "https://hm.com/qa", a: "" },
  { id: 332, n: "zara qatar", c: "fashion", u: "https://zara.com/qa", a: "" },
  { id: 333, n: "bershka qatar", c: "fashion", u: "https://bershka.com/qa", a: "" },
  { id: 334, n: "pull and bear qatar", c: "fashion", u: "https://pullandbear.com/qa", a: "" },
  { id: 335, n: "stradivarius qatar", c: "fashion", u: "https://stradivarius.com/qa", a: "" },
  { id: 336, n: "massimo dutti qatar", c: "fashion", u: "https://massimodutti.com/qa", a: "" },
  { id: 337, n: "oysho qatar", c: "fashion", u: "https://oysho.com/qa", a: "" },
  { id: 338, n: "mango qatar", c: "fashion", u: "https://shop.mango.com/qa", a: "" },
  { id: 339, n: "next qatar", c: "fashion", u: "https://next.qa", a: "" },
  { id: 340, n: "lc waikiki qatar", c: "fashion", u: "https://lcwaikiki.qa", a: "" },
  { id: 341, n: "defacto qatar", c: "fashion", u: "https://defacto.com/qa", a: "" },
  { id: 342, n: "redtag qatar", c: "fashion", u: "https://redtag-stores.com/qa", a: "" },
  { id: 343, n: "max fashion qatar", c: "fashion", u: "https://maxfashion.com/qa", a: "" },
  { id: 344, n: "splash fashion qatar", c: "fashion", u: "https://splashfashions.com/qa", a: "" },
  { id: 345, n: "babyshop qatar", c: "kids fashion", u: "https://babyshopstores.com/qa", a: "" },
  { id: 346, n: "shoe mart qatar", c: "footwear", u: "https://shoemartstores.com/qa", a: "" },
  { id: 347, n: "lifestyle qatar", c: "home decor", u: "https://lifestyleshops.com/qa", a: "" },
  { id: 348, n: "home centre qatar", c: "furniture", u: "https://homecentre.com/qa", a: "" },
  { id: 349, n: "saco qatar", c: "hardware", u: "https://saco.sa/en/qatar", a: "" },
  { id: 350, n: "ace hardware qatar", c: "hardware", u: "https://aceuae.com/qa", a: "" },
  { id: 351, n: "the one qatar", c: "furniture", u: "https://theone.com/qa", a: "" },
  { id: 352, n: "west elm qatar", c: "furniture", u: "https://westelm.me/en-qa", a: "" },
  { id: 353, n: "pottery barn kids qatar", c: "furniture", u: "https://potterybarnkids.me/en-qa", a: "" },
  { id: 354, n: "muji qatar", c: "lifestyle", u: "https://muji.com/qa", a: "" },
  { id: 355, n: "ikea qatar", c: "furniture", u: "https://ikea.com/qa", a: "" },
  { id: 356, n: "homes r us qatar", c: "furniture", u: "https://homesrus.qa", a: "" },
  { id: 357, n: "al jaber optics qatar", c: "optics", u: "https://aljaberopticians.com", a: "" },
  { id: 358, n: "magrabi optical qatar", c: "optics", u: "https://magrabi.com", a: "" },
  { id: 359, n: "yateem opticians qatar", c: "optics", u: "https://yateemoptician.com", a: "" },
  { id: 360, n: "optica qatar", c: "optics", u: "https://optica.net", a: "" },



  { id: 361, n: "damas jewellery qatar", c: "jewelry", u: "https://damasjewellery.com", a: "" },
  { id: 362, n: "joyalukkas jewellery qatar", c: "jewelry", u: "https://joyalukkas.qa", a: "" },
  { id: 363, n: "malabar gold qatar", c: "jewelry", u: "https://malabargoldanddiamonds.com", a: "" },
  { id: 364, n: "sky jewellery qatar", c: "jewelry", u: "https://skyjewellery.com", a: "" },
  { id: 365, n: "al fardan jewellery qatar", c: "jewelry", u: "https://alfardanjewellery.com", a: "" },
  { id: 366, n: "atlas jewellery qatar", c: "jewelry", u: "https://atlasjewellery.com", a: "" },
  { id: 367, n: "kalyan jewellers qatar", c: "jewelry", u: "https://kalyanjewellers.net", a: "" },
  { id: 368, n: "lulu hypermarket qatar", c: "supermarket", u: "https://luluhypermarket.com/en-qa", a: "" },
  { id: 369, n: "al meera consumer goods", c: "supermarket", u: "https://almeera.com.qa", a: "" },
  { id: 370, n: "carrefour hypermarket qatar", c: "supermarket", u: "https://carrefourqatar.com", a: "" },
  { id: 371, n: "monoprix qatar", c: "supermarket", u: "https://monoprix.qa", a: "" },
  { id: 372, n: "family food centre qatar", c: "supermarket", u: "https://ffcqatar.com", a: "" },
  { id: 373, n: "safari hypermarket qatar", c: "supermarket", u: "https://safarihypermarket.com", a: "" },
  { id: 374, n: "grand hypermarket qatar", c: "supermarket", u: "https://grandhyper.com", a: "" },
  { id: 375, n: "nesto hypermarket qatar", c: "supermarket", u: "https://nestogroup.com/qa", a: "" },
  { id: 376, n: "new indian supermarket qatar", c: "supermarket", u: "https://newindiansupermarket.com", a: "" },
  { id: 377, n: "al rawabi food center qatar", c: "supermarket", u: "https://alrawabigroup.com", a: "" },
  { id: 378, n: "safa hypermarket qatar", c: "supermarket", u: "https://safahypermarket.com", a: "" },
  { id: 379, n: "q-mart qatar", c: "supermarket", u: "https://qmart.qa", a: "" },
  { id: 380, n: "al rayyan hypermarket qatar", c: "supermarket", u: "https://alrayyan.qa", a: "" },
  { id: 381, n: "my choice hypermarket qatar", c: "supermarket", u: "https://mychoice.qa", a: "" },
  { id: 382, n: "doha city hypermarket qatar", c: "supermarket", u: "https://dohacityhyper.qa", a: "" },
  { id: 383, n: "kfc restaurant qatar", c: "restaurant", u: "https://qatar.kfc.me", a: "" },
  { id: 384, n: "pizza hut restaurant qatar", c: "restaurant", u: "https://pizzahut.qa", a: "" },
  { id: 385, n: "dominos pizza qatar", c: "restaurant", u: "https://dominos.com.qa", a: "" },
  { id: 386, n: "hardees restaurant qatar", c: "restaurant", u: "https://hardees.qa", a: "" },
  { id: 387, n: "burger king restaurant qatar", c: "restaurant", u: "https://burgerking.qa", a: "" },
  { id: 388, n: "subway restaurant qatar", c: "restaurant", u: "https://subway.com/en-qa", a: "" },
  { id: 389, n: "mcdonalds restaurant qatar", c: "restaurant", u: "https://mcdonalds.com/qa", a: "" },
  { id: 390, n: "baskin robbins qatar", c: "dessert", u: "https://baskinrobbins.qa", a: "" },

  
  { id: 391, n: "dunkin donuts qatar", c: "dessert", u: "https://dunkin.qa", a: "" },
  { id: 392, n: "starbucks coffee qatar", c: "cafe", u: "https://starbucks.qa", a: "" },
  { id: 393, n: "tim hortons qatar", c: "cafe", u: "https://timhortons.qa", a: "" },
  { id: 394, n: "caribou coffee qatar", c: "cafe", u: "https://cariboucoffee.qa", a: "" },
  { id: 395, n: "zaatar w zeit qatar", c: "restaurant", u: "https://zaatarwzeit.net", a: "" },
  { id: 396, n: "applebees qatar", c: "restaurant", u: "https://applebees.qa", a: "" },
  { id: 397, n: "pf changs qatar", c: "restaurant", u: "https://pfchangs.com/qa", a: "" },
  { id: 398, n: "nandos qatar", c: "restaurant", u: "https://nandos.qa", a: "" },
  { id: 399, n: "texas roadhouse qatar", c: "restaurant", u: "https://texasroadhouse.com/qa", a: "" },
  { id: 400, n: "shake shack qatar", c: "restaurant", u: "https://shakeshack.qa", a: "" },
  { id: 401, n: "tgi fridays qatar", c: "restaurant", u: "https://fridays.qa", a: "" },
  { id: 402, n: "dennys qatar", c: "restaurant", u: "https://dennys.qa", a: "" },
  { id: 403, n: "ihop qatar", c: "restaurant", u: "https://ihop.qa", a: "" },
  { id: 404, n: "chilis qatar", c: "restaurant", u: "https://chilis.qa", a: "" },
  { id: 405, n: "mag bakery qatar", c: "bakery", u: "https://magbakery.qa", a: "" },
  { id: 406, n: "doha sweets qatar", c: "bakery", u: "https://dohasweets.com", a: "" },
  { id: 407, n: "al amira sweets qatar", c: "bakery", u: "https://alamirasweets.qa", a: "" },
  { id: 408, n: "karak mquanes qatar", c: "cafe", u: "https://karakmquanes.qa", a: "" },
  { id: 409, n: "halo cafe qatar", c: "cafe", u: "https://halocafe.qa", a: "" },
  { id: 410, n: "flat white coffee qatar", c: "cafe", u: "https://flatwhite.qa", a: "" },
  { id: 411, n: "w cafe qatar", c: "cafe", u: "https://w-doha.com/w-cafe", a: "" },
  { id: 412, n: "cafe 42 qatar", c: "cafe", u: "https://cafe42.qa", a: "" },
  { id: 413, n: "gourmet gulf qatar", c: "food service", u: "https://gourmetgulf.com", a: "" },
  { id: 414, n: "al bake qatar", c: "bakery", u: "https://albake.qa", a: "" },
  { id: 415, n: "saadeddin pastry qatar", c: "bakery", u: "https://saadeddin.com", a: "" },
  { id: 416, n: "al mandarine qatar", c: "bakery", u: "https://almandarine.com", a: "" },
  { id: 417, n: "leto caffe qatar", c: "cafe", u: "https://letocaffe.qa", a: "" },
  { id: 418, n: "espresso lab qatar", c: "cafe", u: "https://espressolab.qa", a: "" },
  { id: 419, n: "percentage coffee qatar", c: "cafe", u: "https://percentage.qa", a: "" },
  { id: 420, n: "viva cafe qatar", c: "cafe", u: "https://vivacafe.qa", a: "" },


  { id: 421, n: "shake it qatar", c: "beverages", u: "https://shakeit.qa", a: "" },
  { id: 422, n: "juicery qatar", c: "beverages", u: "https://juicery.qa", a: "" },
  { id: 423, n: "al jaber watches qatar", c: "watches", u: "https://aljaberwatches.com", a: "" },
  { id: 424, n: "rivoli shop qatar", c: "watches", u: "https://rivoligroup.com", a: "" },
  { id: 425, n: "hour choice qatar", c: "watches", u: "https://hourchoice.com", a: "" },
  { id: 426, n: "aldo accessories qatar", c: "fashion", u: "https://aldoshoes.com.qa", a: "" },
  { id: 427, n: "charles and keith qatar", c: "fashion", u: "https://charleskeith.com/qa", a: "" },
  { id: 428, n: "bath and body works qatar", c: "personal care", u: "https://bathandbodyworks.com.qa", a: "" },
  { id: 429, n: "the body shop qatar", c: "personal care", u: "https://thebodyshop.qa", a: "" },
  { id: 430, n: "loccitane qatar", c: "cosmetics", u: "https://loccitane.qa", a: "" },
  { id: 431, n: "faces qatar", c: "cosmetics", u: "https://faces.com/qa", a: "" },
  { id: 432, n: "ajmal perfumes qatar", c: "fragrances", u: "https://ajmalperfume.com", a: "" },
  { id: 433, n: "arabian oud qatar", c: "fragrances", u: "https://arabianoud.com", a: "" },
  { id: 434, n: "gant qatar", c: "fashion", u: "https://gant.com", a: "" },
  { id: 435, n: "tommy hilfiger qatar", c: "fashion", u: "https://tommy.com", a: "" },
  { id: 436, n: "polo ralph lauren qatar", c: "fashion", u: "https://ralphlauren.com", a: "" },
  { id: 437, n: "timberland qatar", c: "fashion", u: "https://timberland.com", a: "" },
  { id: 438, n: "nike store qatar", c: "sportswear", u: "https://nike.com", a: "" },
  { id: 439, n: "adidas store qatar", c: "sportswear", u: "https://adidas.com", a: "" },
  { id: 440, n: "puma store qatar", c: "sportswear", u: "https://puma.com", a: "" },
  { id: 441, n: "under armour qatar", c: "sportswear", u: "https://underarmour.qa", a: "" },
  { id: 442, n: "go sport qatar", c: "sportswear", u: "https://gosportme.com", a: "" },
  { id: 443, n: "damask furniture qatar", c: "furniture", u: "https://damask.qa", a: "" },
  { id: 444, n: "marina home interiors qatar", c: "furniture", u: "https://marinahomeinteriors.com", a: "" },
  { id: 445, n: "west elm qatar", c: "furniture", u: "https://westelm.me", a: "" },
  { id: 446, n: "pottery barn qatar", c: "furniture", u: "https://potterybarn.me", a: "" },
  { id: 447, n: "crate and barrel qatar", c: "furniture", u: "https://crateandbarrel.me", a: "" },
  { id: 448, n: "pan emirates qatar", c: "furniture", u: "https://panemirates.com", a: "" },
  { id: 449, n: "virgin megastore qatar", c: "electronics", u: "https://virginmegastore.qa", a: "" },
  { id: 450, n: "jarir bookstore qatar", c: "stationery", u: "https://jarir.com/qa", a: "" },


  
  { id: 451, n: "gulf colours qatar", c: "electronics", u: "https://gulfcolours.com", a: "" },
  { id: 452, n: "samsung brand shop qatar", c: "electronics", u: "https://samsung.com/qa", a: "" },
  { id: 453, n: "sony centre qatar", c: "electronics", u: "https://sony.com/qa", a: "" },
  { id: 454, n: "lg brand shop qatar", c: "electronics", u: "https://lg.com/qa", a: "" },
  { id: 455, n: "sharaf dg qatar", c: "electronics", u: "https://dohasooq.com", a: "" },
  { id: 456, n: "e-max qatar", c: "electronics", u: "https://emaxme.com", a: "" },
  { id: 457, n: "qatar tech", c: "electronics", u: "https://qatartech.qa", a: "" },
  { id: 458, n: "alif bookshop", c: "books", u: "https://alifstores.com", a: "" },
  { id: 459, n: "jarir bookstore", c: "books", u: "https://jarir.com/qa", a: "" },
  { id: 460, n: "qatar national library shop", c: "books", u: "https://qnl.qa", a: "" },
  { id: 461, n: "white corner", c: "electronics", u: "https://whitecorner.qa", a: "" },
  { id: 462, n: "tech zone", c: "electronics", u: "https://techzone.qa", a: "" },
  { id: 463, n: "gadget express", c: "electronics", u: "https://gadgetexpress.qa", a: "" },
  { id: 464, n: "mobile store", c: "electronics", u: "https://mobilestore.qa", a: "" },
  { id: 465, n: "computer shop", c: "electronics", u: "https://computershop.qa", a: "" },
  { id: 466, n: "al jaber optics", c: "optics", u: "https://aljaberopticians.com", a: "" },
  { id: 467, n: "magrabi optics", c: "optics", u: "https://magrabi.com", a: "" },
  { id: 468, n: "optica eye care", c: "optics", u: "https://optica.net", a: "" },
  { id: 469, n: "vision express", c: "optics", u: "https://visionexpress.me", a: "" },
  { id: 470, n: "yateem opticians", c: "optics", u: "https://yateemoptician.com", a: "" },
  { id: 471, n: "al razi pharmacy", c: "pharmacy", u: "https://alrazi.qa", a: "" },
  { id: 472, n: "khalifa pharmacy", c: "pharmacy", u: "https://khalifapharmacy.qa", a: "" },
  { id: 473, n: "wellcare pharmacy", c: "pharmacy", u: "https://wellcaregroup.com", a: "" },
  { id: 474, n: "boots pharmacy qatar", c: "pharmacy", u: "https://boots.com", a: "" },
  { id: 475, n: "kulud pharmacy", c: "pharmacy", u: "https://kuludpharmacy.com", a: "" },
  { id: 476, n: "supercare pharmacy", c: "pharmacy", u: "https://supercare.qa", a: "" },
  { id: 477, n: "life pharmacy qatar", c: "pharmacy", u: "https://life-me.com", a: "" },
  { id: 478, n: "al dawaa pharmacy", c: "pharmacy", u: "https://aldawaa.com", a: "" },
  { id: 479, n: "qatar pharmacy", c: "pharmacy", u: "https://qatarpharmacy.qa", a: "" },
  { id: 480, n: "modern pharmacy", c: "pharmacy", u: "https://modernpharmacy.qa", a: "" },
  { id: 481, n: "doha pharmacy", c: "pharmacy", u: "https://dohapharmacy.qa", a: "" },
  { id: 482, n: "city pharmacy", c: "pharmacy", u: "https://citypharmacy.qa", a: "" },
  { id: 483, n: "al watan pharmacy", c: "pharmacy", u: "https://alwatanpharmacy.qa", a: "" },
  { id: 484, n: "al hilal pharmacy", c: "pharmacy", u: "https://alhilalpharmacy.qa", a: "" },
  { id: 485, n: "al sadd pharmacy", c: "pharmacy", u: "https://alsaddpharmacy.qa", a: "" },
  { id: 486, n: "al rayyan pharmacy", c: "pharmacy", u: "https://alrayyanpharmacy.qa", a: "" },
  { id: 487, n: "al wakra pharmacy", c: "pharmacy", u: "https://alwakrapharmacy.qa", a: "" },
  { id: 488, n: "al khor pharmacy", c: "pharmacy", u: "https://alkhorpharmacy.qa", a: "" },
  { id: 489, n: "doha clinic pharmacy", c: "pharmacy", u: "https://dohaclinic.com", a: "" },
  { id: 490, n: "al ahli pharmacy", c: "pharmacy", u: "https://ahlihospital.com", a: "" },
  { id: 491, n: "care n cure pharmacy", c: "pharmacy", u: "https://carencure.qa", a: "" },
  { id: 492, n: "medicare pharmacy", c: "pharmacy", u: "https://medicare.qa", a: "" },
  { id: 493, n: "prime pharmacy", c: "pharmacy", u: "https://primepharmacy.qa", a: "" },
  { id: 494, n: "global pharmacy", c: "pharmacy", u: "https://globalpharmacy.qa", a: "" },
  { id: 495, n: "royal pharmacy", c: "pharmacy", u: "https://royalpharmacy.qa", a: "" },
  { id: 496, n: "gold pharmacy", c: "pharmacy", u: "https://goldpharmacy.qa", a: "" },
  { id: 497, n: "elite pharmacy", c: "pharmacy", u: "https://elitepharmacy.qa", a: "" },
  { id: 498, n: "star pharmacy", c: "pharmacy", u: "https://starpharmacy.qa", a: "" },
  { id: 499, n: "moon pharmacy", c: "pharmacy", u: "https://moonpharmacy.qa", a: "" },
  { id: 500, n: "sun pharmacy", c: "pharmacy", u: "https://sunpharmacy.qa", a: "" }
];


  
  




